import { createFileRoute } from "@tanstack/react-router";
import { useQuery } from "@tanstack/react-query";
import { ShieldCheck, UserPlus, Users } from "lucide-react";
import { useState } from "react";
import { Button } from "@/components/ui/button";
import { DataTable, FilterBar, MetricStrip, PlatformPage, RowMenu, StatusBadge, fetchPlatformRows } from "@/components/platform-page";

export const Route = createFileRoute("/_authenticated/super-admin/admins")({ component: PlatformAdminsPage });
type Admin = { id: string; name: string; email: string; role: string; two_factor_enabled: boolean; last_login: string | null; created_at: string };
function PlatformAdminsPage() { const [search, setSearch] = useState(""); const { data = [], isLoading, error } = useQuery({ queryKey: ["platform-admins"], queryFn: () => fetchPlatformRows<Admin>("platform_admins", "id,name,email,role,two_factor_enabled,last_login,created_at") }); const rows = data.filter((x) => `${x.name} ${x.email} ${x.role}`.toLowerCase().includes(search.toLowerCase())); return <PlatformPage eyebrow="Governance & security" title="Platform admins" description="Control who can administer the SHANSCOTT platform and inspect their access posture." action={<Button className="rounded-xl bg-emerald-600 hover:bg-emerald-700"><UserPlus /> Invite admin</Button>}><MetricStrip items={[{ label: "Administrators", value: data.length, icon: Users }, { label: "2FA enabled", value: data.filter((x) => x.two_factor_enabled).length, icon: ShieldCheck, tone: "blue" }]} /><FilterBar value={search} onChange={setSearch} placeholder="Search by name, email, or role..." /><DataTable columns={["Administrator", "Role", "2FA", "Last login", "Created", "Actions"]} loading={isLoading} error={error ? "Admin directory could not be loaded." : undefined} empty="No platform admins found.">{rows.length ? rows.map((admin) => <tr key={admin.id} className="border-b border-border/60"><td className="px-4 py-4"><p className="font-semibold">{admin.name || "Unnamed admin"}</p><p className="text-xs text-muted-foreground">{admin.email}</p></td><td className="px-4 py-4"><StatusBadge value={admin.role.replaceAll("_", " ")} /></td><td className="px-4 py-4"><StatusBadge value={admin.two_factor_enabled ? "Enabled" : "Not enabled"} /></td><td className="px-4 py-4 text-sm text-muted-foreground">{admin.last_login ? new Date(admin.last_login).toLocaleString() : "Never"}</td><td className="px-4 py-4 text-sm text-muted-foreground">{new Date(admin.created_at).toLocaleDateString()}</td><td className="px-4 py-4"><RowMenu items={[{ label: "Edit role" }, { label: "View activity" }, { label: "Deactivate" }]} /></td></tr>) : undefined}</DataTable></PlatformPage>; }
