import { createFileRoute } from "@tanstack/react-router";
import { useQuery } from "@tanstack/react-query";
import { Activity, FileSearch, ShieldAlert } from "lucide-react";
import { useState } from "react";
import { DataTable, FilterBar, MetricStrip, PlatformPage, RowMenu, fetchPlatformRows } from "@/components/platform-page";

export const Route = createFileRoute("/_authenticated/super-admin/audit-log")({ component: AuditLogPage });
type Log = { id: string; action: string; entity: string; school_id: string | null; actor_id: string; created_at: string; metadata: Record<string, unknown> | null };
function AuditLogPage() { const [search, setSearch] = useState(""); const { data = [], isLoading, error } = useQuery({ queryKey: ["platform-audit-log"], queryFn: () => fetchPlatformRows<Log>("platform_audit_logs", "id,action,entity,school_id,actor_id,created_at,metadata") }); const rows = data.filter((x) => `${x.action} ${x.entity} ${x.school_id ?? ""}`.toLowerCase().includes(search.toLowerCase())); return <PlatformPage eyebrow="Governance & security" title="Audit and security" description="Trace sensitive platform actions, tenant mutations, and administrator activity." action={<button className="rounded-xl border border-border bg-card px-4 py-2 text-sm font-semibold">Export CSV</button>}><MetricStrip items={[{ label: "Recorded events", value: data.length, icon: Activity }, { label: "Tenant mutations", value: data.filter((x) => x.entity === "school").length, icon: FileSearch, tone: "blue" }, { label: "Security events", value: data.filter((x) => `${x.action} ${x.entity}`.toLowerCase().includes("auth")).length, icon: ShieldAlert, tone: "amber" }]} /><FilterBar value={search} onChange={setSearch} placeholder="Filter by action, entity, or tenant..." /><DataTable columns={["Timestamp", "Action", "Entity", "Tenant", "Actor", "Actions"]} loading={isLoading} error={error ? "Audit records could not be loaded." : undefined} empty="No audit events recorded yet.">{rows.length ? rows.map((log) => <tr key={log.id} className="border-b border-border/60"><td className="whitespace-nowrap px-4 py-4 text-xs text-muted-foreground">{new Date(log.created_at).toLocaleString()}</td><td className="px-4 py-4 font-semibold capitalize">{log.action.replaceAll("_", " ")}</td><td className="px-4 py-4 text-sm">{log.entity}</td><td className="px-4 py-4 font-mono text-xs">{log.school_id?.slice(0, 10) ?? "Platform"}</td><td className="px-4 py-4 font-mono text-xs">{log.actor_id.slice(0, 10)}...</td><td className="px-4 py-4"><RowMenu items={[{ label: "View JSON" }, { label: "Open tenant" }]} /></td></tr>) : undefined}</DataTable></PlatformPage>; }
