import { createFileRoute } from "@tanstack/react-router";
import { useQuery } from "@tanstack/react-query";
import { CreditCard, Receipt, TrendingUp } from "lucide-react";
import { MetricStrip, DataTable, FilterBar, PlatformPage, RowMenu, StatusBadge, fetchPlatformRows } from "@/components/platform-page";
import { useState } from "react";

export const Route = createFileRoute("/_authenticated/super-admin/billing")({ component: BillingPage });
type Subscription = { school_id: string; plan: string; status: string; renewal_date: string | null; max_students: number; storage_limit_mb: number };
function BillingPage() { const [search, setSearch] = useState(""); const { data = [], isLoading, error } = useQuery({ queryKey: ["platform-billing"], queryFn: () => fetchPlatformRows<Subscription>("platform_subscriptions", "school_id,plan,status,renewal_date,max_students,storage_limit_mb") }); const rows = data.filter((item) => item.plan.toLowerCase().includes(search.toLowerCase()) || item.school_id.includes(search)); const active = data.filter((item) => item.status === "active").length; const overdue = data.filter((item) => item.status === "past_due").length; return <PlatformPage eyebrow="Core operations" title="Plans and billing" description="Monitor subscription coverage, capacity, renewals, and payment risk across tenants." action={<button className="rounded-xl border border-border bg-card px-4 py-2 text-sm font-semibold">Export ledger</button>}><MetricStrip items={[{ label: "Active subscriptions", value: active, detail: `${data.length} total records`, icon: CreditCard }, { label: "Renewing tenants", value: data.filter((x) => x.renewal_date).length, icon: TrendingUp, tone: "blue" }, { label: "Past due", value: overdue, detail: "Needs follow-up", icon: Receipt, tone: overdue ? "rose" : "emerald" }]} /><div className="space-y-4"><FilterBar value={search} onChange={setSearch} placeholder="Search plan or tenant ID..." /><DataTable columns={["Tenant ID", "Plan", "Status", "Student quota", "Storage", "Renewal", "Actions"]} loading={isLoading} error={error ? "Billing data could not be loaded." : undefined} empty="No subscription records found.">{rows.length ? rows.map((item) => <tr key={item.school_id} className="border-b border-border/60"><td className="px-4 py-4 font-mono text-xs">{item.school_id.slice(0, 12)}...</td><td className="px-4 py-4 font-semibold capitalize">{item.plan}</td><td className="px-4 py-4"><StatusBadge value={item.status} /></td><td className="px-4 py-4 text-sm">{item.max_students.toLocaleString()}</td><td className="px-4 py-4 text-sm">{Math.round(item.storage_limit_mb / 1024)} GB</td><td className="px-4 py-4 text-sm text-muted-foreground">{item.renewal_date ?? "Not scheduled"}</td><td className="px-4 py-4"><RowMenu items={[{ label: "View subscription" }, { label: "Change plan" }, { label: "Open invoice" }]} /></td></tr>) : undefined}</DataTable></div></PlatformPage>; }
