/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SetPasswordRouteImport } from './routes/set-password'
import { Route as AuthenticatedAdmissionsRouteImport } from './routes/_authenticated/admissions'
import { Route as AuthenticatedApprovedAssignmentsRouteImport } from './routes/_authenticated/approved-assignments'
import { Route as AuthenticatedAssessmentApprovalsRouteImport } from './routes/_authenticated/assessment-approvals'
import { Route as AuthenticatedAssessmentsRouteImport } from './routes/_authenticated/assessments'
import { Route as AuthenticatedAssignmentsRouteImport } from './routes/_authenticated/assignments'
import { Route as AuthenticatedAttendanceRouteImport } from './routes/_authenticated/attendance'
import { Route as AuthenticatedAttendanceAnalyticsRouteImport } from './routes/_authenticated/attendance-analytics'
import { Route as AuthenticatedAuditRouteImport } from './routes/_authenticated/audit'
import { Route as AuthenticatedBackupImportRouteImport } from './routes/_authenticated/backup-import'
import { Route as AuthenticatedClassesRouteImport } from './routes/_authenticated/classes'
import { Route as AuthenticatedCurriculumRouteImport } from './routes/_authenticated/curriculum'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedExamTimetableRouteImport } from './routes/_authenticated/exam-timetable'
import { Route as AuthenticatedFinanceRouteImport } from './routes/_authenticated/finance'
import { Route as AuthenticatedGradingRouteImport } from './routes/_authenticated/grading'
import { Route as AuthenticatedLearnersRouteImport } from './routes/_authenticated/learners'
import { Route as AuthenticatedMarksRouteImport } from './routes/_authenticated/marks'
import { Route as AuthenticatedMessagesRouteImport } from './routes/_authenticated/messages'
import { Route as AuthenticatedMyAttendanceRouteImport } from './routes/_authenticated/my-attendance'
import { Route as AuthenticatedMyTeachingRouteImport } from './routes/_authenticated/my-teaching'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedPlatformRouteImport } from './routes/_authenticated/platform'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedPromotionsRouteImport } from './routes/_authenticated/promotions'
import { Route as AuthenticatedReportCardApprovalsRouteImport } from './routes/_authenticated/report-card-approvals'
import { Route as AuthenticatedReportManagementRouteImport } from './routes/_authenticated/report-management'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedSelectRoleRouteImport } from './routes/_authenticated/select-role'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedStaffRouteImport } from './routes/_authenticated/staff'
import { Route as AuthenticatedStaffAttendanceRouteImport } from './routes/_authenticated/staff-attendance'
import { Route as AuthenticatedTimetableRouteImport } from './routes/_authenticated/timetable'
import { Route as AuthenticatedTransitionRouteImport } from './routes/_authenticated/transition'
import { Route as AuthenticatedLearnersLearnerIdRouteImport } from './routes/_authenticated/learners.$learnerId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SetPasswordRoute = SetPasswordRouteImport.update({
  id: '/set-password',
  path: '/set-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdmissionsRoute = AuthenticatedAdmissionsRouteImport.update({
  id: '/admissions',
  path: '/admissions',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedApprovedAssignmentsRoute =
  AuthenticatedApprovedAssignmentsRouteImport.update({
    id: '/approved-assignments',
    path: '/approved-assignments',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAssessmentApprovalsRoute =
  AuthenticatedAssessmentApprovalsRouteImport.update({
    id: '/assessment-approvals',
    path: '/assessment-approvals',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAssessmentsRoute =
  AuthenticatedAssessmentsRouteImport.update({
    id: '/assessments',
    path: '/assessments',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAssignmentsRoute =
  AuthenticatedAssignmentsRouteImport.update({
    id: '/assignments',
    path: '/assignments',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAttendanceRoute = AuthenticatedAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAttendanceAnalyticsRoute =
  AuthenticatedAttendanceAnalyticsRouteImport.update({
    id: '/attendance-analytics',
    path: '/attendance-analytics',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAuditRoute = AuthenticatedAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBackupImportRoute =
  AuthenticatedBackupImportRouteImport.update({
    id: '/backup-import',
    path: '/backup-import',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClassesRoute = AuthenticatedClassesRouteImport.update({
  id: '/classes',
  path: '/classes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCurriculumRoute = AuthenticatedCurriculumRouteImport.update({
  id: '/curriculum',
  path: '/curriculum',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedExamTimetableRoute =
  AuthenticatedExamTimetableRouteImport.update({
    id: '/exam-timetable',
    path: '/exam-timetable',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFinanceRoute = AuthenticatedFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGradingRoute = AuthenticatedGradingRouteImport.update({
  id: '/grading',
  path: '/grading',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLearnersRoute = AuthenticatedLearnersRouteImport.update({
  id: '/learners',
  path: '/learners',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMarksRoute = AuthenticatedMarksRouteImport.update({
  id: '/marks',
  path: '/marks',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMessagesRoute = AuthenticatedMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMyAttendanceRoute =
  AuthenticatedMyAttendanceRouteImport.update({
    id: '/my-attendance',
    path: '/my-attendance',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMyTeachingRoute = AuthenticatedMyTeachingRouteImport.update({
  id: '/my-teaching',
  path: '/my-teaching',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlatformRoute = AuthenticatedPlatformRouteImport.update({
  id: '/platform',
  path: '/platform',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPromotionsRoute = AuthenticatedPromotionsRouteImport.update({
  id: '/promotions',
  path: '/promotions',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportCardApprovalsRoute =
  AuthenticatedReportCardApprovalsRouteImport.update({
    id: '/report-card-approvals',
    path: '/report-card-approvals',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportManagementRoute =
  AuthenticatedReportManagementRouteImport.update({
    id: '/report-management',
    path: '/report-management',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSelectRoleRoute = AuthenticatedSelectRoleRouteImport.update({
  id: '/select-role',
  path: '/select-role',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStaffRoute = AuthenticatedStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStaffAttendanceRoute =
  AuthenticatedStaffAttendanceRouteImport.update({
    id: '/staff-attendance',
    path: '/staff-attendance',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTimetableRoute = AuthenticatedTimetableRouteImport.update({
  id: '/timetable',
  path: '/timetable',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTransitionRoute = AuthenticatedTransitionRouteImport.update({
  id: '/transition',
  path: '/transition',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLearnersLearnerIdRoute =
  AuthenticatedLearnersLearnerIdRouteImport.update({
    id: '/$learnerId',
    path: '/$learnerId',
    getParentRoute: () => AuthenticatedLearnersRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/set-password': typeof SetPasswordRoute
  '/admissions': typeof AuthenticatedAdmissionsRoute
  '/approved-assignments': typeof AuthenticatedApprovedAssignmentsRoute
  '/assessment-approvals': typeof AuthenticatedAssessmentApprovalsRoute
  '/assessments': typeof AuthenticatedAssessmentsRoute
  '/assignments': typeof AuthenticatedAssignmentsRoute
  '/attendance': typeof AuthenticatedAttendanceRoute
  '/attendance-analytics': typeof AuthenticatedAttendanceAnalyticsRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/backup-import': typeof AuthenticatedBackupImportRoute
  '/classes': typeof AuthenticatedClassesRoute
  '/curriculum': typeof AuthenticatedCurriculumRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/exam-timetable': typeof AuthenticatedExamTimetableRoute
  '/finance': typeof AuthenticatedFinanceRoute
  '/grading': typeof AuthenticatedGradingRoute
  '/learners': typeof AuthenticatedLearnersRouteWithChildren
  '/marks': typeof AuthenticatedMarksRoute
  '/messages': typeof AuthenticatedMessagesRoute
  '/my-attendance': typeof AuthenticatedMyAttendanceRoute
  '/my-teaching': typeof AuthenticatedMyTeachingRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/platform': typeof AuthenticatedPlatformRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/promotions': typeof AuthenticatedPromotionsRoute
  '/report-card-approvals': typeof AuthenticatedReportCardApprovalsRoute
  '/report-management': typeof AuthenticatedReportManagementRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/select-role': typeof AuthenticatedSelectRoleRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/staff': typeof AuthenticatedStaffRoute
  '/staff-attendance': typeof AuthenticatedStaffAttendanceRoute
  '/timetable': typeof AuthenticatedTimetableRoute
  '/transition': typeof AuthenticatedTransitionRoute
  '/learners/$learnerId': typeof AuthenticatedLearnersLearnerIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/set-password': typeof SetPasswordRoute
  '/admissions': typeof AuthenticatedAdmissionsRoute
  '/approved-assignments': typeof AuthenticatedApprovedAssignmentsRoute
  '/assessment-approvals': typeof AuthenticatedAssessmentApprovalsRoute
  '/assessments': typeof AuthenticatedAssessmentsRoute
  '/assignments': typeof AuthenticatedAssignmentsRoute
  '/attendance': typeof AuthenticatedAttendanceRoute
  '/attendance-analytics': typeof AuthenticatedAttendanceAnalyticsRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/backup-import': typeof AuthenticatedBackupImportRoute
  '/classes': typeof AuthenticatedClassesRoute
  '/curriculum': typeof AuthenticatedCurriculumRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/exam-timetable': typeof AuthenticatedExamTimetableRoute
  '/finance': typeof AuthenticatedFinanceRoute
  '/grading': typeof AuthenticatedGradingRoute
  '/learners': typeof AuthenticatedLearnersRouteWithChildren
  '/marks': typeof AuthenticatedMarksRoute
  '/messages': typeof AuthenticatedMessagesRoute
  '/my-attendance': typeof AuthenticatedMyAttendanceRoute
  '/my-teaching': typeof AuthenticatedMyTeachingRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/platform': typeof AuthenticatedPlatformRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/promotions': typeof AuthenticatedPromotionsRoute
  '/report-card-approvals': typeof AuthenticatedReportCardApprovalsRoute
  '/report-management': typeof AuthenticatedReportManagementRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/select-role': typeof AuthenticatedSelectRoleRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/staff': typeof AuthenticatedStaffRoute
  '/staff-attendance': typeof AuthenticatedStaffAttendanceRoute
  '/timetable': typeof AuthenticatedTimetableRoute
  '/transition': typeof AuthenticatedTransitionRoute
  '/learners/$learnerId': typeof AuthenticatedLearnersLearnerIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/set-password': typeof SetPasswordRoute
  '/_authenticated/admissions': typeof AuthenticatedAdmissionsRoute
  '/_authenticated/approved-assignments': typeof AuthenticatedApprovedAssignmentsRoute
  '/_authenticated/assessment-approvals': typeof AuthenticatedAssessmentApprovalsRoute
  '/_authenticated/assessments': typeof AuthenticatedAssessmentsRoute
  '/_authenticated/assignments': typeof AuthenticatedAssignmentsRoute
  '/_authenticated/attendance': typeof AuthenticatedAttendanceRoute
  '/_authenticated/attendance-analytics': typeof AuthenticatedAttendanceAnalyticsRoute
  '/_authenticated/audit': typeof AuthenticatedAuditRoute
  '/_authenticated/backup-import': typeof AuthenticatedBackupImportRoute
  '/_authenticated/classes': typeof AuthenticatedClassesRoute
  '/_authenticated/curriculum': typeof AuthenticatedCurriculumRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/exam-timetable': typeof AuthenticatedExamTimetableRoute
  '/_authenticated/finance': typeof AuthenticatedFinanceRoute
  '/_authenticated/grading': typeof AuthenticatedGradingRoute
  '/_authenticated/learners': typeof AuthenticatedLearnersRouteWithChildren
  '/_authenticated/marks': typeof AuthenticatedMarksRoute
  '/_authenticated/messages': typeof AuthenticatedMessagesRoute
  '/_authenticated/my-attendance': typeof AuthenticatedMyAttendanceRoute
  '/_authenticated/my-teaching': typeof AuthenticatedMyTeachingRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/platform': typeof AuthenticatedPlatformRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/promotions': typeof AuthenticatedPromotionsRoute
  '/_authenticated/report-card-approvals': typeof AuthenticatedReportCardApprovalsRoute
  '/_authenticated/report-management': typeof AuthenticatedReportManagementRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/select-role': typeof AuthenticatedSelectRoleRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/staff': typeof AuthenticatedStaffRoute
  '/_authenticated/staff-attendance': typeof AuthenticatedStaffAttendanceRoute
  '/_authenticated/timetable': typeof AuthenticatedTimetableRoute
  '/_authenticated/transition': typeof AuthenticatedTransitionRoute
  '/_authenticated/learners/$learnerId': typeof AuthenticatedLearnersLearnerIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/set-password'
    | '/admissions'
    | '/approved-assignments'
    | '/assessment-approvals'
    | '/assessments'
    | '/assignments'
    | '/attendance'
    | '/attendance-analytics'
    | '/audit'
    | '/backup-import'
    | '/classes'
    | '/curriculum'
    | '/dashboard'
    | '/exam-timetable'
    | '/finance'
    | '/grading'
    | '/learners'
    | '/marks'
    | '/messages'
    | '/my-attendance'
    | '/my-teaching'
    | '/notifications'
    | '/onboarding'
    | '/platform'
    | '/profile'
    | '/promotions'
    | '/report-card-approvals'
    | '/report-management'
    | '/reports'
    | '/select-role'
    | '/settings'
    | '/staff'
    | '/staff-attendance'
    | '/timetable'
    | '/transition'
    | '/learners/$learnerId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/set-password'
    | '/admissions'
    | '/approved-assignments'
    | '/assessment-approvals'
    | '/assessments'
    | '/assignments'
    | '/attendance'
    | '/attendance-analytics'
    | '/audit'
    | '/backup-import'
    | '/classes'
    | '/curriculum'
    | '/dashboard'
    | '/exam-timetable'
    | '/finance'
    | '/grading'
    | '/learners'
    | '/marks'
    | '/messages'
    | '/my-attendance'
    | '/my-teaching'
    | '/notifications'
    | '/onboarding'
    | '/platform'
    | '/profile'
    | '/promotions'
    | '/report-card-approvals'
    | '/report-management'
    | '/reports'
    | '/select-role'
    | '/settings'
    | '/staff'
    | '/staff-attendance'
    | '/timetable'
    | '/transition'
    | '/learners/$learnerId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/set-password'
    | '/_authenticated/admissions'
    | '/_authenticated/approved-assignments'
    | '/_authenticated/assessment-approvals'
    | '/_authenticated/assessments'
    | '/_authenticated/assignments'
    | '/_authenticated/attendance'
    | '/_authenticated/attendance-analytics'
    | '/_authenticated/audit'
    | '/_authenticated/backup-import'
    | '/_authenticated/classes'
    | '/_authenticated/curriculum'
    | '/_authenticated/dashboard'
    | '/_authenticated/exam-timetable'
    | '/_authenticated/finance'
    | '/_authenticated/grading'
    | '/_authenticated/learners'
    | '/_authenticated/marks'
    | '/_authenticated/messages'
    | '/_authenticated/my-attendance'
    | '/_authenticated/my-teaching'
    | '/_authenticated/notifications'
    | '/_authenticated/onboarding'
    | '/_authenticated/platform'
    | '/_authenticated/profile'
    | '/_authenticated/promotions'
    | '/_authenticated/report-card-approvals'
    | '/_authenticated/report-management'
    | '/_authenticated/reports'
    | '/_authenticated/select-role'
    | '/_authenticated/settings'
    | '/_authenticated/staff'
    | '/_authenticated/staff-attendance'
    | '/_authenticated/timetable'
    | '/_authenticated/transition'
    | '/_authenticated/learners/$learnerId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SetPasswordRoute: typeof SetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/set-password': {
      id: '/set-password'
      path: '/set-password'
      fullPath: '/set-password'
      preLoaderRoute: typeof SetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admissions': {
      id: '/_authenticated/admissions'
      path: '/admissions'
      fullPath: '/admissions'
      preLoaderRoute: typeof AuthenticatedAdmissionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/approved-assignments': {
      id: '/_authenticated/approved-assignments'
      path: '/approved-assignments'
      fullPath: '/approved-assignments'
      preLoaderRoute: typeof AuthenticatedApprovedAssignmentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assessment-approvals': {
      id: '/_authenticated/assessment-approvals'
      path: '/assessment-approvals'
      fullPath: '/assessment-approvals'
      preLoaderRoute: typeof AuthenticatedAssessmentApprovalsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assessments': {
      id: '/_authenticated/assessments'
      path: '/assessments'
      fullPath: '/assessments'
      preLoaderRoute: typeof AuthenticatedAssessmentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assignments': {
      id: '/_authenticated/assignments'
      path: '/assignments'
      fullPath: '/assignments'
      preLoaderRoute: typeof AuthenticatedAssignmentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/attendance': {
      id: '/_authenticated/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AuthenticatedAttendanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/attendance-analytics': {
      id: '/_authenticated/attendance-analytics'
      path: '/attendance-analytics'
      fullPath: '/attendance-analytics'
      preLoaderRoute: typeof AuthenticatedAttendanceAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/audit': {
      id: '/_authenticated/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuthenticatedAuditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/backup-import': {
      id: '/_authenticated/backup-import'
      path: '/backup-import'
      fullPath: '/backup-import'
      preLoaderRoute: typeof AuthenticatedBackupImportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/classes': {
      id: '/_authenticated/classes'
      path: '/classes'
      fullPath: '/classes'
      preLoaderRoute: typeof AuthenticatedClassesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/curriculum': {
      id: '/_authenticated/curriculum'
      path: '/curriculum'
      fullPath: '/curriculum'
      preLoaderRoute: typeof AuthenticatedCurriculumRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/exam-timetable': {
      id: '/_authenticated/exam-timetable'
      path: '/exam-timetable'
      fullPath: '/exam-timetable'
      preLoaderRoute: typeof AuthenticatedExamTimetableRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/finance': {
      id: '/_authenticated/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof AuthenticatedFinanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/grading': {
      id: '/_authenticated/grading'
      path: '/grading'
      fullPath: '/grading'
      preLoaderRoute: typeof AuthenticatedGradingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/learners': {
      id: '/_authenticated/learners'
      path: '/learners'
      fullPath: '/learners'
      preLoaderRoute: typeof AuthenticatedLearnersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/marks': {
      id: '/_authenticated/marks'
      path: '/marks'
      fullPath: '/marks'
      preLoaderRoute: typeof AuthenticatedMarksRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/messages': {
      id: '/_authenticated/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof AuthenticatedMessagesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/my-attendance': {
      id: '/_authenticated/my-attendance'
      path: '/my-attendance'
      fullPath: '/my-attendance'
      preLoaderRoute: typeof AuthenticatedMyAttendanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/my-teaching': {
      id: '/_authenticated/my-teaching'
      path: '/my-teaching'
      fullPath: '/my-teaching'
      preLoaderRoute: typeof AuthenticatedMyTeachingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/platform': {
      id: '/_authenticated/platform'
      path: '/platform'
      fullPath: '/platform'
      preLoaderRoute: typeof AuthenticatedPlatformRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/promotions': {
      id: '/_authenticated/promotions'
      path: '/promotions'
      fullPath: '/promotions'
      preLoaderRoute: typeof AuthenticatedPromotionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/report-card-approvals': {
      id: '/_authenticated/report-card-approvals'
      path: '/report-card-approvals'
      fullPath: '/report-card-approvals'
      preLoaderRoute: typeof AuthenticatedReportCardApprovalsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/report-management': {
      id: '/_authenticated/report-management'
      path: '/report-management'
      fullPath: '/report-management'
      preLoaderRoute: typeof AuthenticatedReportManagementRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/select-role': {
      id: '/_authenticated/select-role'
      path: '/select-role'
      fullPath: '/select-role'
      preLoaderRoute: typeof AuthenticatedSelectRoleRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/staff': {
      id: '/_authenticated/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof AuthenticatedStaffRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/staff-attendance': {
      id: '/_authenticated/staff-attendance'
      path: '/staff-attendance'
      fullPath: '/staff-attendance'
      preLoaderRoute: typeof AuthenticatedStaffAttendanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/timetable': {
      id: '/_authenticated/timetable'
      path: '/timetable'
      fullPath: '/timetable'
      preLoaderRoute: typeof AuthenticatedTimetableRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/transition': {
      id: '/_authenticated/transition'
      path: '/transition'
      fullPath: '/transition'
      preLoaderRoute: typeof AuthenticatedTransitionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/learners/$learnerId': {
      id: '/_authenticated/learners/$learnerId'
      path: '/$learnerId'
      fullPath: '/learners/$learnerId'
      preLoaderRoute: typeof AuthenticatedLearnersLearnerIdRouteImport
      parentRoute: typeof AuthenticatedLearnersRoute
    }
  }
}

interface AuthenticatedLearnersRouteChildren {
  AuthenticatedLearnersLearnerIdRoute: typeof AuthenticatedLearnersLearnerIdRoute
}

const AuthenticatedLearnersRouteChildren: AuthenticatedLearnersRouteChildren = {
  AuthenticatedLearnersLearnerIdRoute: AuthenticatedLearnersLearnerIdRoute,
}

const AuthenticatedLearnersRouteWithChildren =
  AuthenticatedLearnersRoute._addFileChildren(
    AuthenticatedLearnersRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdmissionsRoute: typeof AuthenticatedAdmissionsRoute
  AuthenticatedApprovedAssignmentsRoute: typeof AuthenticatedApprovedAssignmentsRoute
  AuthenticatedAssessmentApprovalsRoute: typeof AuthenticatedAssessmentApprovalsRoute
  AuthenticatedAssessmentsRoute: typeof AuthenticatedAssessmentsRoute
  AuthenticatedAssignmentsRoute: typeof AuthenticatedAssignmentsRoute
  AuthenticatedAttendanceRoute: typeof AuthenticatedAttendanceRoute
  AuthenticatedAttendanceAnalyticsRoute: typeof AuthenticatedAttendanceAnalyticsRoute
  AuthenticatedAuditRoute: typeof AuthenticatedAuditRoute
  AuthenticatedBackupImportRoute: typeof AuthenticatedBackupImportRoute
  AuthenticatedClassesRoute: typeof AuthenticatedClassesRoute
  AuthenticatedCurriculumRoute: typeof AuthenticatedCurriculumRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedExamTimetableRoute: typeof AuthenticatedExamTimetableRoute
  AuthenticatedFinanceRoute: typeof AuthenticatedFinanceRoute
  AuthenticatedGradingRoute: typeof AuthenticatedGradingRoute
  AuthenticatedLearnersRoute: typeof AuthenticatedLearnersRouteWithChildren
  AuthenticatedMarksRoute: typeof AuthenticatedMarksRoute
  AuthenticatedMessagesRoute: typeof AuthenticatedMessagesRoute
  AuthenticatedMyAttendanceRoute: typeof AuthenticatedMyAttendanceRoute
  AuthenticatedMyTeachingRoute: typeof AuthenticatedMyTeachingRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedPlatformRoute: typeof AuthenticatedPlatformRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedPromotionsRoute: typeof AuthenticatedPromotionsRoute
  AuthenticatedReportCardApprovalsRoute: typeof AuthenticatedReportCardApprovalsRoute
  AuthenticatedReportManagementRoute: typeof AuthenticatedReportManagementRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedSelectRoleRoute: typeof AuthenticatedSelectRoleRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedStaffRoute: typeof AuthenticatedStaffRoute
  AuthenticatedStaffAttendanceRoute: typeof AuthenticatedStaffAttendanceRoute
  AuthenticatedTimetableRoute: typeof AuthenticatedTimetableRoute
  AuthenticatedTransitionRoute: typeof AuthenticatedTransitionRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdmissionsRoute: AuthenticatedAdmissionsRoute,
  AuthenticatedApprovedAssignmentsRoute: AuthenticatedApprovedAssignmentsRoute,
  AuthenticatedAssessmentApprovalsRoute: AuthenticatedAssessmentApprovalsRoute,
  AuthenticatedAssessmentsRoute: AuthenticatedAssessmentsRoute,
  AuthenticatedAssignmentsRoute: AuthenticatedAssignmentsRoute,
  AuthenticatedAttendanceRoute: AuthenticatedAttendanceRoute,
  AuthenticatedAttendanceAnalyticsRoute: AuthenticatedAttendanceAnalyticsRoute,
  AuthenticatedAuditRoute: AuthenticatedAuditRoute,
  AuthenticatedBackupImportRoute: AuthenticatedBackupImportRoute,
  AuthenticatedClassesRoute: AuthenticatedClassesRoute,
  AuthenticatedCurriculumRoute: AuthenticatedCurriculumRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedExamTimetableRoute: AuthenticatedExamTimetableRoute,
  AuthenticatedFinanceRoute: AuthenticatedFinanceRoute,
  AuthenticatedGradingRoute: AuthenticatedGradingRoute,
  AuthenticatedLearnersRoute: AuthenticatedLearnersRouteWithChildren,
  AuthenticatedMarksRoute: AuthenticatedMarksRoute,
  AuthenticatedMessagesRoute: AuthenticatedMessagesRoute,
  AuthenticatedMyAttendanceRoute: AuthenticatedMyAttendanceRoute,
  AuthenticatedMyTeachingRoute: AuthenticatedMyTeachingRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedPlatformRoute: AuthenticatedPlatformRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedPromotionsRoute: AuthenticatedPromotionsRoute,
  AuthenticatedReportCardApprovalsRoute: AuthenticatedReportCardApprovalsRoute,
  AuthenticatedReportManagementRoute: AuthenticatedReportManagementRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedSelectRoleRoute: AuthenticatedSelectRoleRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedStaffRoute: AuthenticatedStaffRoute,
  AuthenticatedStaffAttendanceRoute: AuthenticatedStaffAttendanceRoute,
  AuthenticatedTimetableRoute: AuthenticatedTimetableRoute,
  AuthenticatedTransitionRoute: AuthenticatedTransitionRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SetPasswordRoute: SetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
