/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SetPasswordRouteImport } from './routes/set-password'
import { Route as AuthenticatedAdmissionsRouteImport } from './routes/_authenticated/admissions'
import { Route as AuthenticatedApprovedAssignmentsRouteImport } from './routes/_authenticated/approved-assignments'
import { Route as AuthenticatedAssessmentApprovalsRouteImport } from './routes/_authenticated/assessment-approvals'
import { Route as AuthenticatedAssessmentsRouteImport } from './routes/_authenticated/assessments'
import { Route as AuthenticatedAssignmentsRouteImport } from './routes/_authenticated/assignments'
import { Route as AuthenticatedAttendanceRouteImport } from './routes/_authenticated/attendance'
import { Route as AuthenticatedAttendanceAnalyticsRouteImport } from './routes/_authenticated/attendance-analytics'
import { Route as AuthenticatedAuditRouteImport } from './routes/_authenticated/audit'
import { Route as AuthenticatedBackupImportRouteImport } from './routes/_authenticated/backup-import'
import { Route as AuthenticatedClassesRouteImport } from './routes/_authenticated/classes'
import { Route as AuthenticatedCurriculumRouteImport } from './routes/_authenticated/curriculum'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedExamTimetableRouteImport } from './routes/_authenticated/exam-timetable'
import { Route as AuthenticatedFinanceRouteImport } from './routes/_authenticated/finance'
import { Route as AuthenticatedFinanceFeeStructureRouteImport } from './routes/_authenticated/finance-fee-structure'
import { Route as AuthenticatedFinanceGeneralLedgerRouteImport } from './routes/_authenticated/finance-general-ledger'
import { Route as AuthenticatedFinanceInventoryRouteImport } from './routes/_authenticated/finance-inventory'
import { Route as AuthenticatedFinanceInvoicesRouteImport } from './routes/_authenticated/finance-invoices'
import { Route as AuthenticatedFinancePaymentSettingsRouteImport } from './routes/_authenticated/finance-payment-settings'
import { Route as AuthenticatedFinancePaymentsRouteImport } from './routes/_authenticated/finance-payments'
import { Route as AuthenticatedFinanceStatementsRouteImport } from './routes/_authenticated/finance-statements'
import { Route as AuthenticatedGeneralLedgerRouteImport } from './routes/_authenticated/general-ledger'
import { Route as AuthenticatedGradingRouteImport } from './routes/_authenticated/grading'
import { Route as AuthenticatedInventoryRouteImport } from './routes/_authenticated/inventory'
import { Route as AuthenticatedLearnersRouteImport } from './routes/_authenticated/learners'
import { Route as AuthenticatedMarksRouteImport } from './routes/_authenticated/marks'
import { Route as AuthenticatedMessagesRouteImport } from './routes/_authenticated/messages'
import { Route as AuthenticatedMyAttendanceRouteImport } from './routes/_authenticated/my-attendance'
import { Route as AuthenticatedMyClassesRouteImport } from './routes/_authenticated/my-classes'
import { Route as AuthenticatedMyTeachingRouteImport } from './routes/_authenticated/my-teaching'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedParentsRouteImport } from './routes/_authenticated/parents'
import { Route as AuthenticatedPerformanceSummaryRouteImport } from './routes/_authenticated/performance-summary'
import { Route as AuthenticatedPlatformRouteImport } from './routes/_authenticated/platform'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedPromotionsRouteImport } from './routes/_authenticated/promotions'
import { Route as AuthenticatedReportCardApprovalsRouteImport } from './routes/_authenticated/report-card-approvals'
import { Route as AuthenticatedReportManagementRouteImport } from './routes/_authenticated/report-management'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedSecurityRouteImport } from './routes/_authenticated/security'
import { Route as AuthenticatedSelectRoleRouteImport } from './routes/_authenticated/select-role'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedSmsCreditsRouteImport } from './routes/_authenticated/sms-credits'
import { Route as AuthenticatedStaffRouteImport } from './routes/_authenticated/staff'
import { Route as AuthenticatedStaffAttendanceRouteImport } from './routes/_authenticated/staff-attendance'
import { Route as AuthenticatedStudentPositionsRouteImport } from './routes/_authenticated/student-positions'
import { Route as AuthenticatedSuperAdminRouteImport } from './routes/_authenticated/super-admin'
import { Route as AuthenticatedTimetableRouteImport } from './routes/_authenticated/timetable'
import { Route as AuthenticatedTransitionRouteImport } from './routes/_authenticated/transition'
import { Route as AuthenticatedLearnersLearnerIdRouteImport } from './routes/_authenticated/learners.$learnerId'
import { Route as AuthenticatedSecurityHistoryRouteImport } from './routes/_authenticated/security.history'
import { Route as AuthenticatedSecurityReportsRouteImport } from './routes/_authenticated/security.reports'
import { Route as AuthenticatedSecurityTodayRouteImport } from './routes/_authenticated/security.today'
import { Route as AuthenticatedSuperAdminIndexRouteImport } from './routes/_authenticated/super-admin/index'
import { Route as AuthenticatedSuperAdminAcademicsRouteImport } from './routes/_authenticated/super-admin/academics'
import { Route as AuthenticatedSuperAdminAdminsRouteImport } from './routes/_authenticated/super-admin/admins'
import { Route as AuthenticatedSuperAdminAnalyticsRouteImport } from './routes/_authenticated/super-admin/analytics'
import { Route as AuthenticatedSuperAdminAnnouncementsRouteImport } from './routes/_authenticated/super-admin/announcements'
import { Route as AuthenticatedSuperAdminAuditLogRouteImport } from './routes/_authenticated/super-admin/audit-log'
import { Route as AuthenticatedSuperAdminBillingRouteImport } from './routes/_authenticated/super-admin/billing'
import { Route as AuthenticatedSuperAdminDataRouteImport } from './routes/_authenticated/super-admin/data'
import { Route as AuthenticatedSuperAdminIntegrationsRouteImport } from './routes/_authenticated/super-admin/integrations'
import { Route as AuthenticatedSuperAdminSchoolsRouteImport } from './routes/_authenticated/super-admin/schools'
import { Route as AuthenticatedSuperAdminSettingsRouteImport } from './routes/_authenticated/super-admin/settings'
import { Route as AuthenticatedSuperAdminSmsCreditsRouteImport } from './routes/_authenticated/super-admin/sms-credits'
import { Route as AuthenticatedSuperAdminSupportRouteImport } from './routes/_authenticated/super-admin/support'
import { Route as AuthenticatedSuperAdminSystemRouteImport } from './routes/_authenticated/super-admin/system'
import { Route as AuthenticatedSuperAdminUsersRouteImport } from './routes/_authenticated/super-admin/users'
import { Route as AuthenticatedSuperAdminSchoolsSchoolIdRouteImport } from './routes/_authenticated/super-admin/schools/$schoolId'
import { Route as AuthenticatedSuperAdminSchoolsNewRouteImport } from './routes/_authenticated/super-admin/schools/new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SetPasswordRoute = SetPasswordRouteImport.update({
  id: '/set-password',
  path: '/set-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdmissionsRoute = AuthenticatedAdmissionsRouteImport.update({
  id: '/admissions',
  path: '/admissions',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedApprovedAssignmentsRoute =
  AuthenticatedApprovedAssignmentsRouteImport.update({
    id: '/approved-assignments',
    path: '/approved-assignments',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAssessmentApprovalsRoute =
  AuthenticatedAssessmentApprovalsRouteImport.update({
    id: '/assessment-approvals',
    path: '/assessment-approvals',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAssessmentsRoute =
  AuthenticatedAssessmentsRouteImport.update({
    id: '/assessments',
    path: '/assessments',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAssignmentsRoute =
  AuthenticatedAssignmentsRouteImport.update({
    id: '/assignments',
    path: '/assignments',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAttendanceRoute = AuthenticatedAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAttendanceAnalyticsRoute =
  AuthenticatedAttendanceAnalyticsRouteImport.update({
    id: '/attendance-analytics',
    path: '/attendance-analytics',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAuditRoute = AuthenticatedAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBackupImportRoute =
  AuthenticatedBackupImportRouteImport.update({
    id: '/backup-import',
    path: '/backup-import',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClassesRoute = AuthenticatedClassesRouteImport.update({
  id: '/classes',
  path: '/classes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCurriculumRoute = AuthenticatedCurriculumRouteImport.update({
  id: '/curriculum',
  path: '/curriculum',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedExamTimetableRoute =
  AuthenticatedExamTimetableRouteImport.update({
    id: '/exam-timetable',
    path: '/exam-timetable',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFinanceRoute = AuthenticatedFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFinanceFeeStructureRoute =
  AuthenticatedFinanceFeeStructureRouteImport.update({
    id: '/finance-fee-structure',
    path: '/finance-fee-structure',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFinanceGeneralLedgerRoute =
  AuthenticatedFinanceGeneralLedgerRouteImport.update({
    id: '/finance-general-ledger',
    path: '/finance-general-ledger',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFinanceInventoryRoute =
  AuthenticatedFinanceInventoryRouteImport.update({
    id: '/finance-inventory',
    path: '/finance-inventory',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFinanceInvoicesRoute =
  AuthenticatedFinanceInvoicesRouteImport.update({
    id: '/finance-invoices',
    path: '/finance-invoices',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFinancePaymentSettingsRoute =
  AuthenticatedFinancePaymentSettingsRouteImport.update({
    id: '/finance-payment-settings',
    path: '/finance-payment-settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFinancePaymentsRoute =
  AuthenticatedFinancePaymentsRouteImport.update({
    id: '/finance-payments',
    path: '/finance-payments',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFinanceStatementsRoute =
  AuthenticatedFinanceStatementsRouteImport.update({
    id: '/finance-statements',
    path: '/finance-statements',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGeneralLedgerRoute =
  AuthenticatedGeneralLedgerRouteImport.update({
    id: '/general-ledger',
    path: '/general-ledger',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGradingRoute = AuthenticatedGradingRouteImport.update({
  id: '/grading',
  path: '/grading',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInventoryRoute = AuthenticatedInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLearnersRoute = AuthenticatedLearnersRouteImport.update({
  id: '/learners',
  path: '/learners',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMarksRoute = AuthenticatedMarksRouteImport.update({
  id: '/marks',
  path: '/marks',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMessagesRoute = AuthenticatedMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMyAttendanceRoute =
  AuthenticatedMyAttendanceRouteImport.update({
    id: '/my-attendance',
    path: '/my-attendance',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMyClassesRoute = AuthenticatedMyClassesRouteImport.update({
  id: '/my-classes',
  path: '/my-classes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMyTeachingRoute = AuthenticatedMyTeachingRouteImport.update({
  id: '/my-teaching',
  path: '/my-teaching',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedParentsRoute = AuthenticatedParentsRouteImport.update({
  id: '/parents',
  path: '/parents',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPerformanceSummaryRoute =
  AuthenticatedPerformanceSummaryRouteImport.update({
    id: '/performance-summary',
    path: '/performance-summary',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPlatformRoute = AuthenticatedPlatformRouteImport.update({
  id: '/platform',
  path: '/platform',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPromotionsRoute = AuthenticatedPromotionsRouteImport.update({
  id: '/promotions',
  path: '/promotions',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportCardApprovalsRoute =
  AuthenticatedReportCardApprovalsRouteImport.update({
    id: '/report-card-approvals',
    path: '/report-card-approvals',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportManagementRoute =
  AuthenticatedReportManagementRouteImport.update({
    id: '/report-management',
    path: '/report-management',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSecurityRoute = AuthenticatedSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSelectRoleRoute = AuthenticatedSelectRoleRouteImport.update({
  id: '/select-role',
  path: '/select-role',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSmsCreditsRoute = AuthenticatedSmsCreditsRouteImport.update({
  id: '/sms-credits',
  path: '/sms-credits',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStaffRoute = AuthenticatedStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStaffAttendanceRoute =
  AuthenticatedStaffAttendanceRouteImport.update({
    id: '/staff-attendance',
    path: '/staff-attendance',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStudentPositionsRoute =
  AuthenticatedStudentPositionsRouteImport.update({
    id: '/student-positions',
    path: '/student-positions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSuperAdminRoute = AuthenticatedSuperAdminRouteImport.update({
  id: '/super-admin',
  path: '/super-admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTimetableRoute = AuthenticatedTimetableRouteImport.update({
  id: '/timetable',
  path: '/timetable',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTransitionRoute = AuthenticatedTransitionRouteImport.update({
  id: '/transition',
  path: '/transition',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLearnersLearnerIdRoute =
  AuthenticatedLearnersLearnerIdRouteImport.update({
    id: '/$learnerId',
    path: '/$learnerId',
    getParentRoute: () => AuthenticatedLearnersRoute,
  } as any)
const AuthenticatedSecurityHistoryRoute =
  AuthenticatedSecurityHistoryRouteImport.update({
    id: '/history',
    path: '/history',
    getParentRoute: () => AuthenticatedSecurityRoute,
  } as any)
const AuthenticatedSecurityReportsRoute =
  AuthenticatedSecurityReportsRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => AuthenticatedSecurityRoute,
  } as any)
const AuthenticatedSecurityTodayRoute =
  AuthenticatedSecurityTodayRouteImport.update({
    id: '/today',
    path: '/today',
    getParentRoute: () => AuthenticatedSecurityRoute,
  } as any)
const AuthenticatedSuperAdminIndexRoute =
  AuthenticatedSuperAdminIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSuperAdminRoute,
  } as any)
const AuthenticatedSuperAdminAcademicsRoute =
  AuthenticatedSuperAdminAcademicsRouteImport.update({
    id: '/academics',
    path: '/academics',
    getParentRoute: () => AuthenticatedSuperAdminRoute,
  } as any)
const AuthenticatedSuperAdminAdminsRoute =
  AuthenticatedSuperAdminAdminsRouteImport.update({
    id: '/admins',
    path: '/admins',
    getParentRoute: () => AuthenticatedSuperAdminRoute,
  } as any)
const AuthenticatedSuperAdminAnalyticsRoute =
  AuthenticatedSuperAdminAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedSuperAdminRoute,
  } as any)
const AuthenticatedSuperAdminAnnouncementsRoute =
  AuthenticatedSuperAdminAnnouncementsRouteImport.update({
    id: '/announcements',
    path: '/announcements',
    getParentRoute: () => AuthenticatedSuperAdminRoute,
  } as any)
const AuthenticatedSuperAdminAuditLogRoute =
  AuthenticatedSuperAdminAuditLogRouteImport.update({
    id: '/audit-log',
    path: '/audit-log',
    getParentRoute: () => AuthenticatedSuperAdminRoute,
  } as any)
const AuthenticatedSuperAdminBillingRoute =
  AuthenticatedSuperAdminBillingRouteImport.update({
    id: '/billing',
    path: '/billing',
    getParentRoute: () => AuthenticatedSuperAdminRoute,
  } as any)
const AuthenticatedSuperAdminDataRoute =
  AuthenticatedSuperAdminDataRouteImport.update({
    id: '/data',
    path: '/data',
    getParentRoute: () => AuthenticatedSuperAdminRoute,
  } as any)
const AuthenticatedSuperAdminIntegrationsRoute =
  AuthenticatedSuperAdminIntegrationsRouteImport.update({
    id: '/integrations',
    path: '/integrations',
    getParentRoute: () => AuthenticatedSuperAdminRoute,
  } as any)
const AuthenticatedSuperAdminSchoolsRoute =
  AuthenticatedSuperAdminSchoolsRouteImport.update({
    id: '/schools',
    path: '/schools',
    getParentRoute: () => AuthenticatedSuperAdminRoute,
  } as any)
const AuthenticatedSuperAdminSettingsRoute =
  AuthenticatedSuperAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedSuperAdminRoute,
  } as any)
const AuthenticatedSuperAdminSmsCreditsRoute =
  AuthenticatedSuperAdminSmsCreditsRouteImport.update({
    id: '/sms-credits',
    path: '/sms-credits',
    getParentRoute: () => AuthenticatedSuperAdminRoute,
  } as any)
const AuthenticatedSuperAdminSupportRoute =
  AuthenticatedSuperAdminSupportRouteImport.update({
    id: '/support',
    path: '/support',
    getParentRoute: () => AuthenticatedSuperAdminRoute,
  } as any)
const AuthenticatedSuperAdminSystemRoute =
  AuthenticatedSuperAdminSystemRouteImport.update({
    id: '/system',
    path: '/system',
    getParentRoute: () => AuthenticatedSuperAdminRoute,
  } as any)
const AuthenticatedSuperAdminUsersRoute =
  AuthenticatedSuperAdminUsersRouteImport.update({
    id: '/users',
    path: '/users',
    getParentRoute: () => AuthenticatedSuperAdminRoute,
  } as any)
const AuthenticatedSuperAdminSchoolsSchoolIdRoute =
  AuthenticatedSuperAdminSchoolsSchoolIdRouteImport.update({
    id: '/$schoolId',
    path: '/$schoolId',
    getParentRoute: () => AuthenticatedSuperAdminSchoolsRoute,
  } as any)
const AuthenticatedSuperAdminSchoolsNewRoute =
  AuthenticatedSuperAdminSchoolsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedSuperAdminSchoolsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/set-password': typeof SetPasswordRoute
  '/admissions': typeof AuthenticatedAdmissionsRoute
  '/approved-assignments': typeof AuthenticatedApprovedAssignmentsRoute
  '/assessment-approvals': typeof AuthenticatedAssessmentApprovalsRoute
  '/assessments': typeof AuthenticatedAssessmentsRoute
  '/assignments': typeof AuthenticatedAssignmentsRoute
  '/attendance': typeof AuthenticatedAttendanceRoute
  '/attendance-analytics': typeof AuthenticatedAttendanceAnalyticsRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/backup-import': typeof AuthenticatedBackupImportRoute
  '/classes': typeof AuthenticatedClassesRoute
  '/curriculum': typeof AuthenticatedCurriculumRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/exam-timetable': typeof AuthenticatedExamTimetableRoute
  '/finance': typeof AuthenticatedFinanceRoute
  '/finance-fee-structure': typeof AuthenticatedFinanceFeeStructureRoute
  '/finance-general-ledger': typeof AuthenticatedFinanceGeneralLedgerRoute
  '/finance-inventory': typeof AuthenticatedFinanceInventoryRoute
  '/finance-invoices': typeof AuthenticatedFinanceInvoicesRoute
  '/finance-payment-settings': typeof AuthenticatedFinancePaymentSettingsRoute
  '/finance-payments': typeof AuthenticatedFinancePaymentsRoute
  '/finance-statements': typeof AuthenticatedFinanceStatementsRoute
  '/general-ledger': typeof AuthenticatedGeneralLedgerRoute
  '/grading': typeof AuthenticatedGradingRoute
  '/inventory': typeof AuthenticatedInventoryRoute
  '/learners': typeof AuthenticatedLearnersRouteWithChildren
  '/marks': typeof AuthenticatedMarksRoute
  '/messages': typeof AuthenticatedMessagesRoute
  '/my-attendance': typeof AuthenticatedMyAttendanceRoute
  '/my-classes': typeof AuthenticatedMyClassesRoute
  '/my-teaching': typeof AuthenticatedMyTeachingRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/parents': typeof AuthenticatedParentsRoute
  '/performance-summary': typeof AuthenticatedPerformanceSummaryRoute
  '/platform': typeof AuthenticatedPlatformRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/promotions': typeof AuthenticatedPromotionsRoute
  '/report-card-approvals': typeof AuthenticatedReportCardApprovalsRoute
  '/report-management': typeof AuthenticatedReportManagementRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/security': typeof AuthenticatedSecurityRouteWithChildren
  '/select-role': typeof AuthenticatedSelectRoleRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/sms-credits': typeof AuthenticatedSmsCreditsRoute
  '/staff': typeof AuthenticatedStaffRoute
  '/staff-attendance': typeof AuthenticatedStaffAttendanceRoute
  '/student-positions': typeof AuthenticatedStudentPositionsRoute
  '/super-admin': typeof AuthenticatedSuperAdminRouteWithChildren
  '/timetable': typeof AuthenticatedTimetableRoute
  '/transition': typeof AuthenticatedTransitionRoute
  '/learners/$learnerId': typeof AuthenticatedLearnersLearnerIdRoute
  '/security/history': typeof AuthenticatedSecurityHistoryRoute
  '/security/reports': typeof AuthenticatedSecurityReportsRoute
  '/security/today': typeof AuthenticatedSecurityTodayRoute
  '/super-admin/academics': typeof AuthenticatedSuperAdminAcademicsRoute
  '/super-admin/admins': typeof AuthenticatedSuperAdminAdminsRoute
  '/super-admin/analytics': typeof AuthenticatedSuperAdminAnalyticsRoute
  '/super-admin/announcements': typeof AuthenticatedSuperAdminAnnouncementsRoute
  '/super-admin/audit-log': typeof AuthenticatedSuperAdminAuditLogRoute
  '/super-admin/billing': typeof AuthenticatedSuperAdminBillingRoute
  '/super-admin/data': typeof AuthenticatedSuperAdminDataRoute
  '/super-admin/integrations': typeof AuthenticatedSuperAdminIntegrationsRoute
  '/super-admin/schools': typeof AuthenticatedSuperAdminSchoolsRouteWithChildren
  '/super-admin/settings': typeof AuthenticatedSuperAdminSettingsRoute
  '/super-admin/sms-credits': typeof AuthenticatedSuperAdminSmsCreditsRoute
  '/super-admin/support': typeof AuthenticatedSuperAdminSupportRoute
  '/super-admin/system': typeof AuthenticatedSuperAdminSystemRoute
  '/super-admin/users': typeof AuthenticatedSuperAdminUsersRoute
  '/super-admin/': typeof AuthenticatedSuperAdminIndexRoute
  '/super-admin/schools/$schoolId': typeof AuthenticatedSuperAdminSchoolsSchoolIdRoute
  '/super-admin/schools/new': typeof AuthenticatedSuperAdminSchoolsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/set-password': typeof SetPasswordRoute
  '/admissions': typeof AuthenticatedAdmissionsRoute
  '/approved-assignments': typeof AuthenticatedApprovedAssignmentsRoute
  '/assessment-approvals': typeof AuthenticatedAssessmentApprovalsRoute
  '/assessments': typeof AuthenticatedAssessmentsRoute
  '/assignments': typeof AuthenticatedAssignmentsRoute
  '/attendance': typeof AuthenticatedAttendanceRoute
  '/attendance-analytics': typeof AuthenticatedAttendanceAnalyticsRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/backup-import': typeof AuthenticatedBackupImportRoute
  '/classes': typeof AuthenticatedClassesRoute
  '/curriculum': typeof AuthenticatedCurriculumRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/exam-timetable': typeof AuthenticatedExamTimetableRoute
  '/finance': typeof AuthenticatedFinanceRoute
  '/finance-fee-structure': typeof AuthenticatedFinanceFeeStructureRoute
  '/finance-general-ledger': typeof AuthenticatedFinanceGeneralLedgerRoute
  '/finance-inventory': typeof AuthenticatedFinanceInventoryRoute
  '/finance-invoices': typeof AuthenticatedFinanceInvoicesRoute
  '/finance-payment-settings': typeof AuthenticatedFinancePaymentSettingsRoute
  '/finance-payments': typeof AuthenticatedFinancePaymentsRoute
  '/finance-statements': typeof AuthenticatedFinanceStatementsRoute
  '/general-ledger': typeof AuthenticatedGeneralLedgerRoute
  '/grading': typeof AuthenticatedGradingRoute
  '/inventory': typeof AuthenticatedInventoryRoute
  '/learners': typeof AuthenticatedLearnersRouteWithChildren
  '/marks': typeof AuthenticatedMarksRoute
  '/messages': typeof AuthenticatedMessagesRoute
  '/my-attendance': typeof AuthenticatedMyAttendanceRoute
  '/my-classes': typeof AuthenticatedMyClassesRoute
  '/my-teaching': typeof AuthenticatedMyTeachingRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/parents': typeof AuthenticatedParentsRoute
  '/performance-summary': typeof AuthenticatedPerformanceSummaryRoute
  '/platform': typeof AuthenticatedPlatformRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/promotions': typeof AuthenticatedPromotionsRoute
  '/report-card-approvals': typeof AuthenticatedReportCardApprovalsRoute
  '/report-management': typeof AuthenticatedReportManagementRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/security': typeof AuthenticatedSecurityRouteWithChildren
  '/select-role': typeof AuthenticatedSelectRoleRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/sms-credits': typeof AuthenticatedSmsCreditsRoute
  '/staff': typeof AuthenticatedStaffRoute
  '/staff-attendance': typeof AuthenticatedStaffAttendanceRoute
  '/student-positions': typeof AuthenticatedStudentPositionsRoute
  '/timetable': typeof AuthenticatedTimetableRoute
  '/transition': typeof AuthenticatedTransitionRoute
  '/learners/$learnerId': typeof AuthenticatedLearnersLearnerIdRoute
  '/security/history': typeof AuthenticatedSecurityHistoryRoute
  '/security/reports': typeof AuthenticatedSecurityReportsRoute
  '/security/today': typeof AuthenticatedSecurityTodayRoute
  '/super-admin/academics': typeof AuthenticatedSuperAdminAcademicsRoute
  '/super-admin/admins': typeof AuthenticatedSuperAdminAdminsRoute
  '/super-admin/analytics': typeof AuthenticatedSuperAdminAnalyticsRoute
  '/super-admin/announcements': typeof AuthenticatedSuperAdminAnnouncementsRoute
  '/super-admin/audit-log': typeof AuthenticatedSuperAdminAuditLogRoute
  '/super-admin/billing': typeof AuthenticatedSuperAdminBillingRoute
  '/super-admin/data': typeof AuthenticatedSuperAdminDataRoute
  '/super-admin/integrations': typeof AuthenticatedSuperAdminIntegrationsRoute
  '/super-admin/schools': typeof AuthenticatedSuperAdminSchoolsRouteWithChildren
  '/super-admin/settings': typeof AuthenticatedSuperAdminSettingsRoute
  '/super-admin/sms-credits': typeof AuthenticatedSuperAdminSmsCreditsRoute
  '/super-admin/support': typeof AuthenticatedSuperAdminSupportRoute
  '/super-admin/system': typeof AuthenticatedSuperAdminSystemRoute
  '/super-admin/users': typeof AuthenticatedSuperAdminUsersRoute
  '/super-admin': typeof AuthenticatedSuperAdminIndexRoute
  '/super-admin/schools/$schoolId': typeof AuthenticatedSuperAdminSchoolsSchoolIdRoute
  '/super-admin/schools/new': typeof AuthenticatedSuperAdminSchoolsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/set-password': typeof SetPasswordRoute
  '/_authenticated/admissions': typeof AuthenticatedAdmissionsRoute
  '/_authenticated/approved-assignments': typeof AuthenticatedApprovedAssignmentsRoute
  '/_authenticated/assessment-approvals': typeof AuthenticatedAssessmentApprovalsRoute
  '/_authenticated/assessments': typeof AuthenticatedAssessmentsRoute
  '/_authenticated/assignments': typeof AuthenticatedAssignmentsRoute
  '/_authenticated/attendance': typeof AuthenticatedAttendanceRoute
  '/_authenticated/attendance-analytics': typeof AuthenticatedAttendanceAnalyticsRoute
  '/_authenticated/audit': typeof AuthenticatedAuditRoute
  '/_authenticated/backup-import': typeof AuthenticatedBackupImportRoute
  '/_authenticated/classes': typeof AuthenticatedClassesRoute
  '/_authenticated/curriculum': typeof AuthenticatedCurriculumRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/exam-timetable': typeof AuthenticatedExamTimetableRoute
  '/_authenticated/finance': typeof AuthenticatedFinanceRoute
  '/_authenticated/finance-fee-structure': typeof AuthenticatedFinanceFeeStructureRoute
  '/_authenticated/finance-general-ledger': typeof AuthenticatedFinanceGeneralLedgerRoute
  '/_authenticated/finance-inventory': typeof AuthenticatedFinanceInventoryRoute
  '/_authenticated/finance-invoices': typeof AuthenticatedFinanceInvoicesRoute
  '/_authenticated/finance-payment-settings': typeof AuthenticatedFinancePaymentSettingsRoute
  '/_authenticated/finance-payments': typeof AuthenticatedFinancePaymentsRoute
  '/_authenticated/finance-statements': typeof AuthenticatedFinanceStatementsRoute
  '/_authenticated/general-ledger': typeof AuthenticatedGeneralLedgerRoute
  '/_authenticated/grading': typeof AuthenticatedGradingRoute
  '/_authenticated/inventory': typeof AuthenticatedInventoryRoute
  '/_authenticated/learners': typeof AuthenticatedLearnersRouteWithChildren
  '/_authenticated/marks': typeof AuthenticatedMarksRoute
  '/_authenticated/messages': typeof AuthenticatedMessagesRoute
  '/_authenticated/my-attendance': typeof AuthenticatedMyAttendanceRoute
  '/_authenticated/my-classes': typeof AuthenticatedMyClassesRoute
  '/_authenticated/my-teaching': typeof AuthenticatedMyTeachingRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/parents': typeof AuthenticatedParentsRoute
  '/_authenticated/performance-summary': typeof AuthenticatedPerformanceSummaryRoute
  '/_authenticated/platform': typeof AuthenticatedPlatformRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/promotions': typeof AuthenticatedPromotionsRoute
  '/_authenticated/report-card-approvals': typeof AuthenticatedReportCardApprovalsRoute
  '/_authenticated/report-management': typeof AuthenticatedReportManagementRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/security': typeof AuthenticatedSecurityRouteWithChildren
  '/_authenticated/select-role': typeof AuthenticatedSelectRoleRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/sms-credits': typeof AuthenticatedSmsCreditsRoute
  '/_authenticated/staff': typeof AuthenticatedStaffRoute
  '/_authenticated/staff-attendance': typeof AuthenticatedStaffAttendanceRoute
  '/_authenticated/student-positions': typeof AuthenticatedStudentPositionsRoute
  '/_authenticated/super-admin': typeof AuthenticatedSuperAdminRouteWithChildren
  '/_authenticated/timetable': typeof AuthenticatedTimetableRoute
  '/_authenticated/transition': typeof AuthenticatedTransitionRoute
  '/_authenticated/learners/$learnerId': typeof AuthenticatedLearnersLearnerIdRoute
  '/_authenticated/security/history': typeof AuthenticatedSecurityHistoryRoute
  '/_authenticated/security/reports': typeof AuthenticatedSecurityReportsRoute
  '/_authenticated/security/today': typeof AuthenticatedSecurityTodayRoute
  '/_authenticated/super-admin/academics': typeof AuthenticatedSuperAdminAcademicsRoute
  '/_authenticated/super-admin/admins': typeof AuthenticatedSuperAdminAdminsRoute
  '/_authenticated/super-admin/analytics': typeof AuthenticatedSuperAdminAnalyticsRoute
  '/_authenticated/super-admin/announcements': typeof AuthenticatedSuperAdminAnnouncementsRoute
  '/_authenticated/super-admin/audit-log': typeof AuthenticatedSuperAdminAuditLogRoute
  '/_authenticated/super-admin/billing': typeof AuthenticatedSuperAdminBillingRoute
  '/_authenticated/super-admin/data': typeof AuthenticatedSuperAdminDataRoute
  '/_authenticated/super-admin/integrations': typeof AuthenticatedSuperAdminIntegrationsRoute
  '/_authenticated/super-admin/schools': typeof AuthenticatedSuperAdminSchoolsRouteWithChildren
  '/_authenticated/super-admin/settings': typeof AuthenticatedSuperAdminSettingsRoute
  '/_authenticated/super-admin/sms-credits': typeof AuthenticatedSuperAdminSmsCreditsRoute
  '/_authenticated/super-admin/support': typeof AuthenticatedSuperAdminSupportRoute
  '/_authenticated/super-admin/system': typeof AuthenticatedSuperAdminSystemRoute
  '/_authenticated/super-admin/users': typeof AuthenticatedSuperAdminUsersRoute
  '/_authenticated/super-admin/': typeof AuthenticatedSuperAdminIndexRoute
  '/_authenticated/super-admin/schools/$schoolId': typeof AuthenticatedSuperAdminSchoolsSchoolIdRoute
  '/_authenticated/super-admin/schools/new': typeof AuthenticatedSuperAdminSchoolsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/set-password'
    | '/admissions'
    | '/approved-assignments'
    | '/assessment-approvals'
    | '/assessments'
    | '/assignments'
    | '/attendance'
    | '/attendance-analytics'
    | '/audit'
    | '/backup-import'
    | '/classes'
    | '/curriculum'
    | '/dashboard'
    | '/exam-timetable'
    | '/finance'
    | '/finance-fee-structure'
    | '/finance-general-ledger'
    | '/finance-inventory'
    | '/finance-invoices'
    | '/finance-payment-settings'
    | '/finance-payments'
    | '/finance-statements'
    | '/general-ledger'
    | '/grading'
    | '/inventory'
    | '/learners'
    | '/marks'
    | '/messages'
    | '/my-attendance'
    | '/my-classes'
    | '/my-teaching'
    | '/notifications'
    | '/onboarding'
    | '/parents'
    | '/performance-summary'
    | '/platform'
    | '/profile'
    | '/promotions'
    | '/report-card-approvals'
    | '/report-management'
    | '/reports'
    | '/security'
    | '/select-role'
    | '/settings'
    | '/sms-credits'
    | '/staff'
    | '/staff-attendance'
    | '/student-positions'
    | '/super-admin'
    | '/timetable'
    | '/transition'
    | '/learners/$learnerId'
    | '/security/history'
    | '/security/reports'
    | '/security/today'
    | '/super-admin/academics'
    | '/super-admin/admins'
    | '/super-admin/analytics'
    | '/super-admin/announcements'
    | '/super-admin/audit-log'
    | '/super-admin/billing'
    | '/super-admin/data'
    | '/super-admin/integrations'
    | '/super-admin/schools'
    | '/super-admin/settings'
    | '/super-admin/sms-credits'
    | '/super-admin/support'
    | '/super-admin/system'
    | '/super-admin/users'
    | '/super-admin/'
    | '/super-admin/schools/$schoolId'
    | '/super-admin/schools/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/set-password'
    | '/admissions'
    | '/approved-assignments'
    | '/assessment-approvals'
    | '/assessments'
    | '/assignments'
    | '/attendance'
    | '/attendance-analytics'
    | '/audit'
    | '/backup-import'
    | '/classes'
    | '/curriculum'
    | '/dashboard'
    | '/exam-timetable'
    | '/finance'
    | '/finance-fee-structure'
    | '/finance-general-ledger'
    | '/finance-inventory'
    | '/finance-invoices'
    | '/finance-payment-settings'
    | '/finance-payments'
    | '/finance-statements'
    | '/general-ledger'
    | '/grading'
    | '/inventory'
    | '/learners'
    | '/marks'
    | '/messages'
    | '/my-attendance'
    | '/my-classes'
    | '/my-teaching'
    | '/notifications'
    | '/onboarding'
    | '/parents'
    | '/performance-summary'
    | '/platform'
    | '/profile'
    | '/promotions'
    | '/report-card-approvals'
    | '/report-management'
    | '/reports'
    | '/security'
    | '/select-role'
    | '/settings'
    | '/sms-credits'
    | '/staff'
    | '/staff-attendance'
    | '/student-positions'
    | '/timetable'
    | '/transition'
    | '/learners/$learnerId'
    | '/security/history'
    | '/security/reports'
    | '/security/today'
    | '/super-admin/academics'
    | '/super-admin/admins'
    | '/super-admin/analytics'
    | '/super-admin/announcements'
    | '/super-admin/audit-log'
    | '/super-admin/billing'
    | '/super-admin/data'
    | '/super-admin/integrations'
    | '/super-admin/schools'
    | '/super-admin/settings'
    | '/super-admin/sms-credits'
    | '/super-admin/support'
    | '/super-admin/system'
    | '/super-admin/users'
    | '/super-admin'
    | '/super-admin/schools/$schoolId'
    | '/super-admin/schools/new'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/set-password'
    | '/_authenticated/admissions'
    | '/_authenticated/approved-assignments'
    | '/_authenticated/assessment-approvals'
    | '/_authenticated/assessments'
    | '/_authenticated/assignments'
    | '/_authenticated/attendance'
    | '/_authenticated/attendance-analytics'
    | '/_authenticated/audit'
    | '/_authenticated/backup-import'
    | '/_authenticated/classes'
    | '/_authenticated/curriculum'
    | '/_authenticated/dashboard'
    | '/_authenticated/exam-timetable'
    | '/_authenticated/finance'
    | '/_authenticated/finance-fee-structure'
    | '/_authenticated/finance-general-ledger'
    | '/_authenticated/finance-inventory'
    | '/_authenticated/finance-invoices'
    | '/_authenticated/finance-payment-settings'
    | '/_authenticated/finance-payments'
    | '/_authenticated/finance-statements'
    | '/_authenticated/general-ledger'
    | '/_authenticated/grading'
    | '/_authenticated/inventory'
    | '/_authenticated/learners'
    | '/_authenticated/marks'
    | '/_authenticated/messages'
    | '/_authenticated/my-attendance'
    | '/_authenticated/my-classes'
    | '/_authenticated/my-teaching'
    | '/_authenticated/notifications'
    | '/_authenticated/onboarding'
    | '/_authenticated/parents'
    | '/_authenticated/performance-summary'
    | '/_authenticated/platform'
    | '/_authenticated/profile'
    | '/_authenticated/promotions'
    | '/_authenticated/report-card-approvals'
    | '/_authenticated/report-management'
    | '/_authenticated/reports'
    | '/_authenticated/security'
    | '/_authenticated/select-role'
    | '/_authenticated/settings'
    | '/_authenticated/sms-credits'
    | '/_authenticated/staff'
    | '/_authenticated/staff-attendance'
    | '/_authenticated/student-positions'
    | '/_authenticated/super-admin'
    | '/_authenticated/timetable'
    | '/_authenticated/transition'
    | '/_authenticated/learners/$learnerId'
    | '/_authenticated/security/history'
    | '/_authenticated/security/reports'
    | '/_authenticated/security/today'
    | '/_authenticated/super-admin/academics'
    | '/_authenticated/super-admin/admins'
    | '/_authenticated/super-admin/analytics'
    | '/_authenticated/super-admin/announcements'
    | '/_authenticated/super-admin/audit-log'
    | '/_authenticated/super-admin/billing'
    | '/_authenticated/super-admin/data'
    | '/_authenticated/super-admin/integrations'
    | '/_authenticated/super-admin/schools'
    | '/_authenticated/super-admin/settings'
    | '/_authenticated/super-admin/sms-credits'
    | '/_authenticated/super-admin/support'
    | '/_authenticated/super-admin/system'
    | '/_authenticated/super-admin/users'
    | '/_authenticated/super-admin/'
    | '/_authenticated/super-admin/schools/$schoolId'
    | '/_authenticated/super-admin/schools/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SetPasswordRoute: typeof SetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/set-password': {
      id: '/set-password'
      path: '/set-password'
      fullPath: '/set-password'
      preLoaderRoute: typeof SetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admissions': {
      id: '/_authenticated/admissions'
      path: '/admissions'
      fullPath: '/admissions'
      preLoaderRoute: typeof AuthenticatedAdmissionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/approved-assignments': {
      id: '/_authenticated/approved-assignments'
      path: '/approved-assignments'
      fullPath: '/approved-assignments'
      preLoaderRoute: typeof AuthenticatedApprovedAssignmentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assessment-approvals': {
      id: '/_authenticated/assessment-approvals'
      path: '/assessment-approvals'
      fullPath: '/assessment-approvals'
      preLoaderRoute: typeof AuthenticatedAssessmentApprovalsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assessments': {
      id: '/_authenticated/assessments'
      path: '/assessments'
      fullPath: '/assessments'
      preLoaderRoute: typeof AuthenticatedAssessmentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assignments': {
      id: '/_authenticated/assignments'
      path: '/assignments'
      fullPath: '/assignments'
      preLoaderRoute: typeof AuthenticatedAssignmentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/attendance': {
      id: '/_authenticated/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AuthenticatedAttendanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/attendance-analytics': {
      id: '/_authenticated/attendance-analytics'
      path: '/attendance-analytics'
      fullPath: '/attendance-analytics'
      preLoaderRoute: typeof AuthenticatedAttendanceAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/audit': {
      id: '/_authenticated/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuthenticatedAuditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/backup-import': {
      id: '/_authenticated/backup-import'
      path: '/backup-import'
      fullPath: '/backup-import'
      preLoaderRoute: typeof AuthenticatedBackupImportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/classes': {
      id: '/_authenticated/classes'
      path: '/classes'
      fullPath: '/classes'
      preLoaderRoute: typeof AuthenticatedClassesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/curriculum': {
      id: '/_authenticated/curriculum'
      path: '/curriculum'
      fullPath: '/curriculum'
      preLoaderRoute: typeof AuthenticatedCurriculumRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/exam-timetable': {
      id: '/_authenticated/exam-timetable'
      path: '/exam-timetable'
      fullPath: '/exam-timetable'
      preLoaderRoute: typeof AuthenticatedExamTimetableRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/finance': {
      id: '/_authenticated/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof AuthenticatedFinanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/finance-fee-structure': {
      id: '/_authenticated/finance-fee-structure'
      path: '/finance-fee-structure'
      fullPath: '/finance-fee-structure'
      preLoaderRoute: typeof AuthenticatedFinanceFeeStructureRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/finance-general-ledger': {
      id: '/_authenticated/finance-general-ledger'
      path: '/finance-general-ledger'
      fullPath: '/finance-general-ledger'
      preLoaderRoute: typeof AuthenticatedFinanceGeneralLedgerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/finance-inventory': {
      id: '/_authenticated/finance-inventory'
      path: '/finance-inventory'
      fullPath: '/finance-inventory'
      preLoaderRoute: typeof AuthenticatedFinanceInventoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/finance-invoices': {
      id: '/_authenticated/finance-invoices'
      path: '/finance-invoices'
      fullPath: '/finance-invoices'
      preLoaderRoute: typeof AuthenticatedFinanceInvoicesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/finance-payment-settings': {
      id: '/_authenticated/finance-payment-settings'
      path: '/finance-payment-settings'
      fullPath: '/finance-payment-settings'
      preLoaderRoute: typeof AuthenticatedFinancePaymentSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/finance-payments': {
      id: '/_authenticated/finance-payments'
      path: '/finance-payments'
      fullPath: '/finance-payments'
      preLoaderRoute: typeof AuthenticatedFinancePaymentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/finance-statements': {
      id: '/_authenticated/finance-statements'
      path: '/finance-statements'
      fullPath: '/finance-statements'
      preLoaderRoute: typeof AuthenticatedFinanceStatementsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/general-ledger': {
      id: '/_authenticated/general-ledger'
      path: '/general-ledger'
      fullPath: '/general-ledger'
      preLoaderRoute: typeof AuthenticatedGeneralLedgerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/grading': {
      id: '/_authenticated/grading'
      path: '/grading'
      fullPath: '/grading'
      preLoaderRoute: typeof AuthenticatedGradingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inventory': {
      id: '/_authenticated/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AuthenticatedInventoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/learners': {
      id: '/_authenticated/learners'
      path: '/learners'
      fullPath: '/learners'
      preLoaderRoute: typeof AuthenticatedLearnersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/marks': {
      id: '/_authenticated/marks'
      path: '/marks'
      fullPath: '/marks'
      preLoaderRoute: typeof AuthenticatedMarksRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/messages': {
      id: '/_authenticated/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof AuthenticatedMessagesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/my-attendance': {
      id: '/_authenticated/my-attendance'
      path: '/my-attendance'
      fullPath: '/my-attendance'
      preLoaderRoute: typeof AuthenticatedMyAttendanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/my-classes': {
      id: '/_authenticated/my-classes'
      path: '/my-classes'
      fullPath: '/my-classes'
      preLoaderRoute: typeof AuthenticatedMyClassesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/my-teaching': {
      id: '/_authenticated/my-teaching'
      path: '/my-teaching'
      fullPath: '/my-teaching'
      preLoaderRoute: typeof AuthenticatedMyTeachingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/parents': {
      id: '/_authenticated/parents'
      path: '/parents'
      fullPath: '/parents'
      preLoaderRoute: typeof AuthenticatedParentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/performance-summary': {
      id: '/_authenticated/performance-summary'
      path: '/performance-summary'
      fullPath: '/performance-summary'
      preLoaderRoute: typeof AuthenticatedPerformanceSummaryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/platform': {
      id: '/_authenticated/platform'
      path: '/platform'
      fullPath: '/platform'
      preLoaderRoute: typeof AuthenticatedPlatformRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/promotions': {
      id: '/_authenticated/promotions'
      path: '/promotions'
      fullPath: '/promotions'
      preLoaderRoute: typeof AuthenticatedPromotionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/report-card-approvals': {
      id: '/_authenticated/report-card-approvals'
      path: '/report-card-approvals'
      fullPath: '/report-card-approvals'
      preLoaderRoute: typeof AuthenticatedReportCardApprovalsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/report-management': {
      id: '/_authenticated/report-management'
      path: '/report-management'
      fullPath: '/report-management'
      preLoaderRoute: typeof AuthenticatedReportManagementRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/security': {
      id: '/_authenticated/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof AuthenticatedSecurityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/select-role': {
      id: '/_authenticated/select-role'
      path: '/select-role'
      fullPath: '/select-role'
      preLoaderRoute: typeof AuthenticatedSelectRoleRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sms-credits': {
      id: '/_authenticated/sms-credits'
      path: '/sms-credits'
      fullPath: '/sms-credits'
      preLoaderRoute: typeof AuthenticatedSmsCreditsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/staff': {
      id: '/_authenticated/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof AuthenticatedStaffRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/staff-attendance': {
      id: '/_authenticated/staff-attendance'
      path: '/staff-attendance'
      fullPath: '/staff-attendance'
      preLoaderRoute: typeof AuthenticatedStaffAttendanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/student-positions': {
      id: '/_authenticated/student-positions'
      path: '/student-positions'
      fullPath: '/student-positions'
      preLoaderRoute: typeof AuthenticatedStudentPositionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/super-admin': {
      id: '/_authenticated/super-admin'
      path: '/super-admin'
      fullPath: '/super-admin'
      preLoaderRoute: typeof AuthenticatedSuperAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/timetable': {
      id: '/_authenticated/timetable'
      path: '/timetable'
      fullPath: '/timetable'
      preLoaderRoute: typeof AuthenticatedTimetableRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/transition': {
      id: '/_authenticated/transition'
      path: '/transition'
      fullPath: '/transition'
      preLoaderRoute: typeof AuthenticatedTransitionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/learners/$learnerId': {
      id: '/_authenticated/learners/$learnerId'
      path: '/$learnerId'
      fullPath: '/learners/$learnerId'
      preLoaderRoute: typeof AuthenticatedLearnersLearnerIdRouteImport
      parentRoute: typeof AuthenticatedLearnersRoute
    }
    '/_authenticated/security/history': {
      id: '/_authenticated/security/history'
      path: '/history'
      fullPath: '/security/history'
      preLoaderRoute: typeof AuthenticatedSecurityHistoryRouteImport
      parentRoute: typeof AuthenticatedSecurityRoute
    }
    '/_authenticated/security/reports': {
      id: '/_authenticated/security/reports'
      path: '/reports'
      fullPath: '/security/reports'
      preLoaderRoute: typeof AuthenticatedSecurityReportsRouteImport
      parentRoute: typeof AuthenticatedSecurityRoute
    }
    '/_authenticated/security/today': {
      id: '/_authenticated/security/today'
      path: '/today'
      fullPath: '/security/today'
      preLoaderRoute: typeof AuthenticatedSecurityTodayRouteImport
      parentRoute: typeof AuthenticatedSecurityRoute
    }
    '/_authenticated/super-admin/': {
      id: '/_authenticated/super-admin/'
      path: '/'
      fullPath: '/super-admin/'
      preLoaderRoute: typeof AuthenticatedSuperAdminIndexRouteImport
      parentRoute: typeof AuthenticatedSuperAdminRoute
    }
    '/_authenticated/super-admin/academics': {
      id: '/_authenticated/super-admin/academics'
      path: '/academics'
      fullPath: '/super-admin/academics'
      preLoaderRoute: typeof AuthenticatedSuperAdminAcademicsRouteImport
      parentRoute: typeof AuthenticatedSuperAdminRoute
    }
    '/_authenticated/super-admin/admins': {
      id: '/_authenticated/super-admin/admins'
      path: '/admins'
      fullPath: '/super-admin/admins'
      preLoaderRoute: typeof AuthenticatedSuperAdminAdminsRouteImport
      parentRoute: typeof AuthenticatedSuperAdminRoute
    }
    '/_authenticated/super-admin/analytics': {
      id: '/_authenticated/super-admin/analytics'
      path: '/analytics'
      fullPath: '/super-admin/analytics'
      preLoaderRoute: typeof AuthenticatedSuperAdminAnalyticsRouteImport
      parentRoute: typeof AuthenticatedSuperAdminRoute
    }
    '/_authenticated/super-admin/announcements': {
      id: '/_authenticated/super-admin/announcements'
      path: '/announcements'
      fullPath: '/super-admin/announcements'
      preLoaderRoute: typeof AuthenticatedSuperAdminAnnouncementsRouteImport
      parentRoute: typeof AuthenticatedSuperAdminRoute
    }
    '/_authenticated/super-admin/audit-log': {
      id: '/_authenticated/super-admin/audit-log'
      path: '/audit-log'
      fullPath: '/super-admin/audit-log'
      preLoaderRoute: typeof AuthenticatedSuperAdminAuditLogRouteImport
      parentRoute: typeof AuthenticatedSuperAdminRoute
    }
    '/_authenticated/super-admin/billing': {
      id: '/_authenticated/super-admin/billing'
      path: '/billing'
      fullPath: '/super-admin/billing'
      preLoaderRoute: typeof AuthenticatedSuperAdminBillingRouteImport
      parentRoute: typeof AuthenticatedSuperAdminRoute
    }
    '/_authenticated/super-admin/data': {
      id: '/_authenticated/super-admin/data'
      path: '/data'
      fullPath: '/super-admin/data'
      preLoaderRoute: typeof AuthenticatedSuperAdminDataRouteImport
      parentRoute: typeof AuthenticatedSuperAdminRoute
    }
    '/_authenticated/super-admin/integrations': {
      id: '/_authenticated/super-admin/integrations'
      path: '/integrations'
      fullPath: '/super-admin/integrations'
      preLoaderRoute: typeof AuthenticatedSuperAdminIntegrationsRouteImport
      parentRoute: typeof AuthenticatedSuperAdminRoute
    }
    '/_authenticated/super-admin/schools': {
      id: '/_authenticated/super-admin/schools'
      path: '/schools'
      fullPath: '/super-admin/schools'
      preLoaderRoute: typeof AuthenticatedSuperAdminSchoolsRouteImport
      parentRoute: typeof AuthenticatedSuperAdminRoute
    }
    '/_authenticated/super-admin/settings': {
      id: '/_authenticated/super-admin/settings'
      path: '/settings'
      fullPath: '/super-admin/settings'
      preLoaderRoute: typeof AuthenticatedSuperAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedSuperAdminRoute
    }
    '/_authenticated/super-admin/sms-credits': {
      id: '/_authenticated/super-admin/sms-credits'
      path: '/sms-credits'
      fullPath: '/super-admin/sms-credits'
      preLoaderRoute: typeof AuthenticatedSuperAdminSmsCreditsRouteImport
      parentRoute: typeof AuthenticatedSuperAdminRoute
    }
    '/_authenticated/super-admin/support': {
      id: '/_authenticated/super-admin/support'
      path: '/support'
      fullPath: '/super-admin/support'
      preLoaderRoute: typeof AuthenticatedSuperAdminSupportRouteImport
      parentRoute: typeof AuthenticatedSuperAdminRoute
    }
    '/_authenticated/super-admin/system': {
      id: '/_authenticated/super-admin/system'
      path: '/system'
      fullPath: '/super-admin/system'
      preLoaderRoute: typeof AuthenticatedSuperAdminSystemRouteImport
      parentRoute: typeof AuthenticatedSuperAdminRoute
    }
    '/_authenticated/super-admin/users': {
      id: '/_authenticated/super-admin/users'
      path: '/users'
      fullPath: '/super-admin/users'
      preLoaderRoute: typeof AuthenticatedSuperAdminUsersRouteImport
      parentRoute: typeof AuthenticatedSuperAdminRoute
    }
    '/_authenticated/super-admin/schools/$schoolId': {
      id: '/_authenticated/super-admin/schools/$schoolId'
      path: '/$schoolId'
      fullPath: '/super-admin/schools/$schoolId'
      preLoaderRoute: typeof AuthenticatedSuperAdminSchoolsSchoolIdRouteImport
      parentRoute: typeof AuthenticatedSuperAdminSchoolsRoute
    }
    '/_authenticated/super-admin/schools/new': {
      id: '/_authenticated/super-admin/schools/new'
      path: '/new'
      fullPath: '/super-admin/schools/new'
      preLoaderRoute: typeof AuthenticatedSuperAdminSchoolsNewRouteImport
      parentRoute: typeof AuthenticatedSuperAdminSchoolsRoute
    }
  }
}

interface AuthenticatedLearnersRouteChildren {
  AuthenticatedLearnersLearnerIdRoute: typeof AuthenticatedLearnersLearnerIdRoute
}

const AuthenticatedLearnersRouteChildren: AuthenticatedLearnersRouteChildren = {
  AuthenticatedLearnersLearnerIdRoute: AuthenticatedLearnersLearnerIdRoute,
}

const AuthenticatedLearnersRouteWithChildren =
  AuthenticatedLearnersRoute._addFileChildren(
    AuthenticatedLearnersRouteChildren,
  )

interface AuthenticatedSecurityRouteChildren {
  AuthenticatedSecurityHistoryRoute: typeof AuthenticatedSecurityHistoryRoute
  AuthenticatedSecurityReportsRoute: typeof AuthenticatedSecurityReportsRoute
  AuthenticatedSecurityTodayRoute: typeof AuthenticatedSecurityTodayRoute
}

const AuthenticatedSecurityRouteChildren: AuthenticatedSecurityRouteChildren = {
  AuthenticatedSecurityHistoryRoute: AuthenticatedSecurityHistoryRoute,
  AuthenticatedSecurityReportsRoute: AuthenticatedSecurityReportsRoute,
  AuthenticatedSecurityTodayRoute: AuthenticatedSecurityTodayRoute,
}

const AuthenticatedSecurityRouteWithChildren =
  AuthenticatedSecurityRoute._addFileChildren(
    AuthenticatedSecurityRouteChildren,
  )

interface AuthenticatedSuperAdminSchoolsRouteChildren {
  AuthenticatedSuperAdminSchoolsSchoolIdRoute: typeof AuthenticatedSuperAdminSchoolsSchoolIdRoute
  AuthenticatedSuperAdminSchoolsNewRoute: typeof AuthenticatedSuperAdminSchoolsNewRoute
}

const AuthenticatedSuperAdminSchoolsRouteChildren: AuthenticatedSuperAdminSchoolsRouteChildren =
  {
    AuthenticatedSuperAdminSchoolsSchoolIdRoute:
      AuthenticatedSuperAdminSchoolsSchoolIdRoute,
    AuthenticatedSuperAdminSchoolsNewRoute:
      AuthenticatedSuperAdminSchoolsNewRoute,
  }

const AuthenticatedSuperAdminSchoolsRouteWithChildren =
  AuthenticatedSuperAdminSchoolsRoute._addFileChildren(
    AuthenticatedSuperAdminSchoolsRouteChildren,
  )

interface AuthenticatedSuperAdminRouteChildren {
  AuthenticatedSuperAdminAcademicsRoute: typeof AuthenticatedSuperAdminAcademicsRoute
  AuthenticatedSuperAdminAdminsRoute: typeof AuthenticatedSuperAdminAdminsRoute
  AuthenticatedSuperAdminAnalyticsRoute: typeof AuthenticatedSuperAdminAnalyticsRoute
  AuthenticatedSuperAdminAnnouncementsRoute: typeof AuthenticatedSuperAdminAnnouncementsRoute
  AuthenticatedSuperAdminAuditLogRoute: typeof AuthenticatedSuperAdminAuditLogRoute
  AuthenticatedSuperAdminBillingRoute: typeof AuthenticatedSuperAdminBillingRoute
  AuthenticatedSuperAdminDataRoute: typeof AuthenticatedSuperAdminDataRoute
  AuthenticatedSuperAdminIntegrationsRoute: typeof AuthenticatedSuperAdminIntegrationsRoute
  AuthenticatedSuperAdminSchoolsRoute: typeof AuthenticatedSuperAdminSchoolsRouteWithChildren
  AuthenticatedSuperAdminSettingsRoute: typeof AuthenticatedSuperAdminSettingsRoute
  AuthenticatedSuperAdminSmsCreditsRoute: typeof AuthenticatedSuperAdminSmsCreditsRoute
  AuthenticatedSuperAdminSupportRoute: typeof AuthenticatedSuperAdminSupportRoute
  AuthenticatedSuperAdminSystemRoute: typeof AuthenticatedSuperAdminSystemRoute
  AuthenticatedSuperAdminUsersRoute: typeof AuthenticatedSuperAdminUsersRoute
  AuthenticatedSuperAdminIndexRoute: typeof AuthenticatedSuperAdminIndexRoute
}

const AuthenticatedSuperAdminRouteChildren: AuthenticatedSuperAdminRouteChildren =
  {
    AuthenticatedSuperAdminAcademicsRoute:
      AuthenticatedSuperAdminAcademicsRoute,
    AuthenticatedSuperAdminAdminsRoute: AuthenticatedSuperAdminAdminsRoute,
    AuthenticatedSuperAdminAnalyticsRoute:
      AuthenticatedSuperAdminAnalyticsRoute,
    AuthenticatedSuperAdminAnnouncementsRoute:
      AuthenticatedSuperAdminAnnouncementsRoute,
    AuthenticatedSuperAdminAuditLogRoute: AuthenticatedSuperAdminAuditLogRoute,
    AuthenticatedSuperAdminBillingRoute: AuthenticatedSuperAdminBillingRoute,
    AuthenticatedSuperAdminDataRoute: AuthenticatedSuperAdminDataRoute,
    AuthenticatedSuperAdminIntegrationsRoute:
      AuthenticatedSuperAdminIntegrationsRoute,
    AuthenticatedSuperAdminSchoolsRoute:
      AuthenticatedSuperAdminSchoolsRouteWithChildren,
    AuthenticatedSuperAdminSettingsRoute: AuthenticatedSuperAdminSettingsRoute,
    AuthenticatedSuperAdminSmsCreditsRoute:
      AuthenticatedSuperAdminSmsCreditsRoute,
    AuthenticatedSuperAdminSupportRoute: AuthenticatedSuperAdminSupportRoute,
    AuthenticatedSuperAdminSystemRoute: AuthenticatedSuperAdminSystemRoute,
    AuthenticatedSuperAdminUsersRoute: AuthenticatedSuperAdminUsersRoute,
    AuthenticatedSuperAdminIndexRoute: AuthenticatedSuperAdminIndexRoute,
  }

const AuthenticatedSuperAdminRouteWithChildren =
  AuthenticatedSuperAdminRoute._addFileChildren(
    AuthenticatedSuperAdminRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdmissionsRoute: typeof AuthenticatedAdmissionsRoute
  AuthenticatedApprovedAssignmentsRoute: typeof AuthenticatedApprovedAssignmentsRoute
  AuthenticatedAssessmentApprovalsRoute: typeof AuthenticatedAssessmentApprovalsRoute
  AuthenticatedAssessmentsRoute: typeof AuthenticatedAssessmentsRoute
  AuthenticatedAssignmentsRoute: typeof AuthenticatedAssignmentsRoute
  AuthenticatedAttendanceRoute: typeof AuthenticatedAttendanceRoute
  AuthenticatedAttendanceAnalyticsRoute: typeof AuthenticatedAttendanceAnalyticsRoute
  AuthenticatedAuditRoute: typeof AuthenticatedAuditRoute
  AuthenticatedBackupImportRoute: typeof AuthenticatedBackupImportRoute
  AuthenticatedClassesRoute: typeof AuthenticatedClassesRoute
  AuthenticatedCurriculumRoute: typeof AuthenticatedCurriculumRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedExamTimetableRoute: typeof AuthenticatedExamTimetableRoute
  AuthenticatedFinanceRoute: typeof AuthenticatedFinanceRoute
  AuthenticatedFinanceFeeStructureRoute: typeof AuthenticatedFinanceFeeStructureRoute
  AuthenticatedFinanceGeneralLedgerRoute: typeof AuthenticatedFinanceGeneralLedgerRoute
  AuthenticatedFinanceInventoryRoute: typeof AuthenticatedFinanceInventoryRoute
  AuthenticatedFinanceInvoicesRoute: typeof AuthenticatedFinanceInvoicesRoute
  AuthenticatedFinancePaymentSettingsRoute: typeof AuthenticatedFinancePaymentSettingsRoute
  AuthenticatedFinancePaymentsRoute: typeof AuthenticatedFinancePaymentsRoute
  AuthenticatedFinanceStatementsRoute: typeof AuthenticatedFinanceStatementsRoute
  AuthenticatedGeneralLedgerRoute: typeof AuthenticatedGeneralLedgerRoute
  AuthenticatedGradingRoute: typeof AuthenticatedGradingRoute
  AuthenticatedInventoryRoute: typeof AuthenticatedInventoryRoute
  AuthenticatedLearnersRoute: typeof AuthenticatedLearnersRouteWithChildren
  AuthenticatedMarksRoute: typeof AuthenticatedMarksRoute
  AuthenticatedMessagesRoute: typeof AuthenticatedMessagesRoute
  AuthenticatedMyAttendanceRoute: typeof AuthenticatedMyAttendanceRoute
  AuthenticatedMyClassesRoute: typeof AuthenticatedMyClassesRoute
  AuthenticatedMyTeachingRoute: typeof AuthenticatedMyTeachingRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedParentsRoute: typeof AuthenticatedParentsRoute
  AuthenticatedPerformanceSummaryRoute: typeof AuthenticatedPerformanceSummaryRoute
  AuthenticatedPlatformRoute: typeof AuthenticatedPlatformRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedPromotionsRoute: typeof AuthenticatedPromotionsRoute
  AuthenticatedReportCardApprovalsRoute: typeof AuthenticatedReportCardApprovalsRoute
  AuthenticatedReportManagementRoute: typeof AuthenticatedReportManagementRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedSecurityRoute: typeof AuthenticatedSecurityRouteWithChildren
  AuthenticatedSelectRoleRoute: typeof AuthenticatedSelectRoleRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedSmsCreditsRoute: typeof AuthenticatedSmsCreditsRoute
  AuthenticatedStaffRoute: typeof AuthenticatedStaffRoute
  AuthenticatedStaffAttendanceRoute: typeof AuthenticatedStaffAttendanceRoute
  AuthenticatedStudentPositionsRoute: typeof AuthenticatedStudentPositionsRoute
  AuthenticatedSuperAdminRoute: typeof AuthenticatedSuperAdminRouteWithChildren
  AuthenticatedTimetableRoute: typeof AuthenticatedTimetableRoute
  AuthenticatedTransitionRoute: typeof AuthenticatedTransitionRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdmissionsRoute: AuthenticatedAdmissionsRoute,
  AuthenticatedApprovedAssignmentsRoute: AuthenticatedApprovedAssignmentsRoute,
  AuthenticatedAssessmentApprovalsRoute: AuthenticatedAssessmentApprovalsRoute,
  AuthenticatedAssessmentsRoute: AuthenticatedAssessmentsRoute,
  AuthenticatedAssignmentsRoute: AuthenticatedAssignmentsRoute,
  AuthenticatedAttendanceRoute: AuthenticatedAttendanceRoute,
  AuthenticatedAttendanceAnalyticsRoute: AuthenticatedAttendanceAnalyticsRoute,
  AuthenticatedAuditRoute: AuthenticatedAuditRoute,
  AuthenticatedBackupImportRoute: AuthenticatedBackupImportRoute,
  AuthenticatedClassesRoute: AuthenticatedClassesRoute,
  AuthenticatedCurriculumRoute: AuthenticatedCurriculumRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedExamTimetableRoute: AuthenticatedExamTimetableRoute,
  AuthenticatedFinanceRoute: AuthenticatedFinanceRoute,
  AuthenticatedFinanceFeeStructureRoute: AuthenticatedFinanceFeeStructureRoute,
  AuthenticatedFinanceGeneralLedgerRoute:
    AuthenticatedFinanceGeneralLedgerRoute,
  AuthenticatedFinanceInventoryRoute: AuthenticatedFinanceInventoryRoute,
  AuthenticatedFinanceInvoicesRoute: AuthenticatedFinanceInvoicesRoute,
  AuthenticatedFinancePaymentSettingsRoute:
    AuthenticatedFinancePaymentSettingsRoute,
  AuthenticatedFinancePaymentsRoute: AuthenticatedFinancePaymentsRoute,
  AuthenticatedFinanceStatementsRoute: AuthenticatedFinanceStatementsRoute,
  AuthenticatedGeneralLedgerRoute: AuthenticatedGeneralLedgerRoute,
  AuthenticatedGradingRoute: AuthenticatedGradingRoute,
  AuthenticatedInventoryRoute: AuthenticatedInventoryRoute,
  AuthenticatedLearnersRoute: AuthenticatedLearnersRouteWithChildren,
  AuthenticatedMarksRoute: AuthenticatedMarksRoute,
  AuthenticatedMessagesRoute: AuthenticatedMessagesRoute,
  AuthenticatedMyAttendanceRoute: AuthenticatedMyAttendanceRoute,
  AuthenticatedMyClassesRoute: AuthenticatedMyClassesRoute,
  AuthenticatedMyTeachingRoute: AuthenticatedMyTeachingRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedParentsRoute: AuthenticatedParentsRoute,
  AuthenticatedPerformanceSummaryRoute: AuthenticatedPerformanceSummaryRoute,
  AuthenticatedPlatformRoute: AuthenticatedPlatformRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedPromotionsRoute: AuthenticatedPromotionsRoute,
  AuthenticatedReportCardApprovalsRoute: AuthenticatedReportCardApprovalsRoute,
  AuthenticatedReportManagementRoute: AuthenticatedReportManagementRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedSecurityRoute: AuthenticatedSecurityRouteWithChildren,
  AuthenticatedSelectRoleRoute: AuthenticatedSelectRoleRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedSmsCreditsRoute: AuthenticatedSmsCreditsRoute,
  AuthenticatedStaffRoute: AuthenticatedStaffRoute,
  AuthenticatedStaffAttendanceRoute: AuthenticatedStaffAttendanceRoute,
  AuthenticatedStudentPositionsRoute: AuthenticatedStudentPositionsRoute,
  AuthenticatedSuperAdminRoute: AuthenticatedSuperAdminRouteWithChildren,
  AuthenticatedTimetableRoute: AuthenticatedTimetableRoute,
  AuthenticatedTransitionRoute: AuthenticatedTransitionRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SetPasswordRoute: SetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
