-- Seed the standard lower-secondary and senior-secondary learning areas for each school.
-- These records are intentionally grade-scoped so they appear in the correct curriculum sections.

INSERT INTO public.learning_areas (school_id, name, code, grades, is_core, education_level)
SELECT s.id, area.name, area.code, area.grades, area.is_core, area.education_level
FROM public.schools s
CROSS JOIN (
  VALUES
    ('English', 'ENG', ARRAY['G7','G8','G9']::public.cbe_grade[], true, 'junior_school'::public.cbe_level),
    ('Kiswahili / Kenyan Sign Language', 'KSL', ARRAY['G7','G8','G9']::public.cbe_grade[], true, 'junior_school'::public.cbe_level),
    ('Mathematics', 'MATH', ARRAY['G7','G8','G9','G10','G11','G12']::public.cbe_grade[], true, 'junior_school'::public.cbe_level),
    ('Integrated Science', 'INT_SCI', ARRAY['G7','G8','G9']::public.cbe_grade[], true, 'junior_school'::public.cbe_level),
    ('Health Education', 'HEALTH', ARRAY['G7','G8','G9']::public.cbe_grade[], true, 'junior_school'::public.cbe_level),
    ('Pre-Technical and Pre-Career Education', 'PTPCE', ARRAY['G7','G8','G9']::public.cbe_grade[], true, 'junior_school'::public.cbe_level),
    ('Social Studies', 'SOC', ARRAY['G7','G8','G9']::public.cbe_grade[], true, 'junior_school'::public.cbe_level),
    ('Religious Education', 'REL', ARRAY['G7','G8','G9']::public.cbe_grade[], true, 'junior_school'::public.cbe_level),
    ('Christian Religious Education', 'CRE', ARRAY['G7','G8','G9','G10','G11','G12']::public.cbe_grade[], false, 'junior_school'::public.cbe_level),
    ('Islamic Religious Education', 'IRE', ARRAY['G7','G8','G9','G10','G11','G12']::public.cbe_grade[], false, 'junior_school'::public.cbe_level),
    ('Hindu Religious Education', 'HRE', ARRAY['G7','G8','G9','G10','G11','G12']::public.cbe_grade[], false, 'junior_school'::public.cbe_level),
    ('Business Studies', 'BUS', ARRAY['G7','G8','G9','G10','G11','G12']::public.cbe_grade[], false, 'junior_school'::public.cbe_level),
    ('Agriculture', 'AGR', ARRAY['G7','G8','G9','G10','G11','G12']::public.cbe_grade[], false, 'junior_school'::public.cbe_level),
    ('Life Skills Education', 'LSE', ARRAY['G7','G8','G9']::public.cbe_grade[], false, 'junior_school'::public.cbe_level),
    ('Sports and Physical Education', 'SPORT', ARRAY['G7','G8','G9']::public.cbe_grade[], false, 'junior_school'::public.cbe_level),
    ('Visual Arts', 'VIS_ART', ARRAY['G7','G8','G9']::public.cbe_grade[], false, 'junior_school'::public.cbe_level),
    ('Performing Arts', 'PERF_ART', ARRAY['G7','G8','G9','G10','G11','G12']::public.cbe_grade[], false, 'junior_school'::public.cbe_level),
    ('Home Science', 'HOME_SCI', ARRAY['G7','G8','G9']::public.cbe_grade[], false, 'junior_school'::public.cbe_level),
    ('Computer Science', 'COMP_SCI', ARRAY['G7','G8','G9','G10','G11','G12']::public.cbe_grade[], false, 'junior_school'::public.cbe_level),
    ('German', 'GER', ARRAY['G7','G8','G9','G10','G11','G12']::public.cbe_grade[], false, 'junior_school'::public.cbe_level),
    ('French', 'FRE', ARRAY['G7','G8','G9','G10','G11','G12']::public.cbe_grade[], false, 'junior_school'::public.cbe_level),
    ('Mandarin', 'MAN', ARRAY['G7','G8','G9','G10','G11','G12']::public.cbe_grade[], false, 'junior_school'::public.cbe_level),
    ('Arabic', 'ARA', ARRAY['G7','G8','G9','G10','G11','G12']::public.cbe_grade[], false, 'junior_school'::public.cbe_level),
    ('Kenyan Sign Language', 'KSL', ARRAY['G7','G8','G9','G10','G11','G12']::public.cbe_grade[], false, 'junior_school'::public.cbe_level),
    ('Indigenous Languages', 'IND_LANG', ARRAY['G7','G8','G9','G10','G11','G12']::public.cbe_grade[], false, 'junior_school'::public.cbe_level),
    ('Community Service Learning', 'CSL', ARRAY['G10','G11','G12']::public.cbe_grade[], true, 'senior_school'::public.cbe_level),
    ('Physical Education', 'PE', ARRAY['G10','G11','G12']::public.cbe_grade[], true, 'senior_school'::public.cbe_level),
    ('Legal and Ethical Issues in Arts', 'ARTS_ETHICS', ARRAY['G10','G11','G12']::public.cbe_grade[], true, 'senior_school'::public.cbe_level),
    ('Communication Skills', 'COMM', ARRAY['G10','G11','G12']::public.cbe_grade[], true, 'senior_school'::public.cbe_level),
    ('Music', 'MUS', ARRAY['G10','G11','G12']::public.cbe_grade[], false, 'senior_school'::public.cbe_level),
    ('Dance', 'DANCE', ARRAY['G10','G11','G12']::public.cbe_grade[], false, 'senior_school'::public.cbe_level),
    ('Theatre and Elocution', 'THEATRE', ARRAY['G10','G11','G12']::public.cbe_grade[], false, 'senior_school'::public.cbe_level),
    ('Visual and Applied Arts', 'VIS_APP', ARRAY['G10','G11','G12']::public.cbe_grade[], false, 'senior_school'::public.cbe_level),
    ('Fine Art', 'FINE_ART', ARRAY['G10','G11','G12']::public.cbe_grade[], false, 'senior_school'::public.cbe_level),
    ('Applied Art', 'APPLIED_ART', ARRAY['G10','G11','G12']::public.cbe_grade[], false, 'senior_school'::public.cbe_level),
    ('Time-Based Media and Crafts', 'MEDIA_CRAFT', ARRAY['G10','G11','G12']::public.cbe_grade[], false, 'senior_school'::public.cbe_level),
    ('Human Physiology, Anatomy and Nutrition', 'HUMAN_PHYS', ARRAY['G10','G11','G12']::public.cbe_grade[], true, 'senior_school'::public.cbe_level),
    ('Sports Ethics', 'SPORTS_ETHICS', ARRAY['G10','G11','G12']::public.cbe_grade[], true, 'senior_school'::public.cbe_level),
    ('Ball Games', 'BALL_GAMES', ARRAY['G10','G11','G12']::public.cbe_grade[], false, 'senior_school'::public.cbe_level),
    ('Athletics', 'ATH', ARRAY['G10','G11','G12']::public.cbe_grade[], false, 'senior_school'::public.cbe_level),
    ('Indoor Games', 'INDOOR_GAMES', ARRAY['G10','G11','G12']::public.cbe_grade[], false, 'senior_school'::public.cbe_level),
    ('Gymnastics', 'GYM', ARRAY['G10','G11','G12']::public.cbe_grade[], false, 'senior_school'::public.cbe_level),
    ('Water Sports', 'WATER_SPORTS', ARRAY['G10','G11','G12']::public.cbe_grade[], false, 'senior_school'::public.cbe_level),
    ('Boxing', 'BOX', ARRAY['G10','G11','G12']::public.cbe_grade[], false, 'senior_school'::public.cbe_level),
    ('Martial Arts', 'MARTIAL_ARTS', ARRAY['G10','G11','G12']::public.cbe_grade[], false, 'senior_school'::public.cbe_level),
    ('Outdoor Pursuits', 'OUTDOOR', ARRAY['G10','G11','G12']::public.cbe_grade[], false, 'senior_school'::public.cbe_level),
    ('Advanced Physical Education', 'ADV_PE', ARRAY['G10','G11','G12']::public.cbe_grade[], false, 'senior_school'::public.cbe_level),
    ('History and Citizenship', 'HIST_CIT', ARRAY['G10','G11','G12']::public.cbe_grade[], false, 'senior_school'::public.cbe_level),
    ('Geography', 'GEO', ARRAY['G10','G11','G12']::public.cbe_grade[], false, 'senior_school'::public.cbe_level),
    ('English Language', 'ENG', ARRAY['G10','G11','G12']::public.cbe_grade[], false, 'senior_school'::public.cbe_level),
    ('Literature in English', 'LIT_ENG', ARRAY['G10','G11','G12']::public.cbe_grade[], false, 'senior_school'::public.cbe_level),
    ('Kiswahili', 'KIS', ARRAY['G10','G11','G12']::public.cbe_grade[], false, 'senior_school'::public.cbe_level),
    ('Fasihi ya Kiswahili', 'FAS_KIS', ARRAY['G10','G11','G12']::public.cbe_grade[], false, 'senior_school'::public.cbe_level),
    ('Physics', 'PHY', ARRAY['G10','G11','G12']::public.cbe_grade[], false, 'senior_school'::public.cbe_level),
    ('Chemistry', 'CHEM', ARRAY['G10','G11','G12']::public.cbe_grade[], false, 'senior_school'::public.cbe_level),
    ('Biology', 'BIO', ARRAY['G10','G11','G12']::public.cbe_grade[], false, 'senior_school'::public.cbe_level),
    ('Foods and Nutrition', 'FOODS', ARRAY['G10','G11','G12']::public.cbe_grade[], false, 'senior_school'::public.cbe_level),
    ('Home Management', 'HOME_MGMT', ARRAY['G10','G11','G12']::public.cbe_grade[], false, 'senior_school'::public.cbe_level),
    ('Agricultural Technology', 'AGR_TECH', ARRAY['G10','G11','G12']::public.cbe_grade[], false, 'senior_school'::public.cbe_level),
    ('Geosciences', 'GEOSCI', ARRAY['G10','G11','G12']::public.cbe_grade[], false, 'senior_school'::public.cbe_level),
    ('Marine and Fisheries Technology', 'MARINE_FISH', ARRAY['G10','G11','G12']::public.cbe_grade[], false, 'senior_school'::public.cbe_level),
    ('Aviation Technology', 'AVIATION', ARRAY['G10','G11','G12']::public.cbe_grade[], false, 'senior_school'::public.cbe_level),
    ('Wood Technology', 'WOOD', ARRAY['G10','G11','G12']::public.cbe_grade[], false, 'senior_school'::public.cbe_level),
    ('Electrical Technology', 'ELEC', ARRAY['G10','G11','G12']::public.cbe_grade[], false, 'senior_school'::public.cbe_level),
    ('Metal Technology', 'METAL', ARRAY['G10','G11','G12']::public.cbe_grade[], false, 'senior_school'::public.cbe_level),
    ('Power Mechanics', 'POWER_MECH', ARRAY['G10','G11','G12']::public.cbe_grade[], false, 'senior_school'::public.cbe_level),
    ('Clothing Technology', 'CLOTHING', ARRAY['G10','G11','G12']::public.cbe_grade[], false, 'senior_school'::public.cbe_level),
    ('Construction Technology', 'CONSTRUCTION', ARRAY['G10','G11','G12']::public.cbe_grade[], false, 'senior_school'::public.cbe_level),
    ('Media Technology', 'MEDIA_TECH', ARRAY['G10','G11','G12']::public.cbe_grade[], false, 'senior_school'::public.cbe_level),
    ('Electronics Technology', 'ELECTRONICS', ARRAY['G10','G11','G12']::public.cbe_grade[], false, 'senior_school'::public.cbe_level),
    ('Manufacturing Technology', 'MANUFACTURE', ARRAY['G10','G11','G12']::public.cbe_grade[], false, 'senior_school'::public.cbe_level),
    ('Mechatronics', 'MECHATRONICS', ARRAY['G10','G11','G12']::public.cbe_grade[], false, 'senior_school'::public.cbe_level),
    ('Garment Making and Interior Design', 'GARMENT', ARRAY['G10','G11','G12']::public.cbe_grade[], false, 'senior_school'::public.cbe_level),
    ('Leather Work', 'LEATHER', ARRAY['G10','G11','G12']::public.cbe_grade[], false, 'senior_school'::public.cbe_level),
    ('Culinary Arts', 'CULINARY', ARRAY['G10','G11','G12']::public.cbe_grade[], false, 'senior_school'::public.cbe_level),
    ('Hair Dressing and Beauty Therapy', 'HAIR_BEAUTY', ARRAY['G10','G11','G12']::public.cbe_grade[], false, 'senior_school'::public.cbe_level),
    ('Plumbing and Ceramics', 'PLUMBING', ARRAY['G10','G11','G12']::public.cbe_grade[], false, 'senior_school'::public.cbe_level),
    ('Welding and Fabrication', 'WELDING', ARRAY['G10','G11','G12']::public.cbe_grade[], false, 'senior_school'::public.cbe_level),
    ('Tourism and Travel', 'TOURISM', ARRAY['G10','G11','G12']::public.cbe_grade[], false, 'senior_school'::public.cbe_level),
    ('Air Conditioning and Refrigeration', 'AC_REFRIG', ARRAY['G10','G11','G12']::public.cbe_grade[], false, 'senior_school'::public.cbe_level),
    ('Animal Keeping', 'ANIMAL_KEEPING', ARRAY['G10','G11','G12']::public.cbe_grade[], false, 'senior_school'::public.cbe_level),
    ('Exterior Design and Landscaping', 'LANDSCAPING', ARRAY['G10','G11','G12']::public.cbe_grade[], false, 'senior_school'::public.cbe_level),
    ('Building Construction', 'BUILDING', ARRAY['G10','G11','G12']::public.cbe_grade[], false, 'senior_school'::public.cbe_level),
    ('Photography', 'PHOTO', ARRAY['G10','G11','G12']::public.cbe_grade[], false, 'senior_school'::public.cbe_level),
    ('Graphic Designing and Animation', 'GRAPHIC_DESIGN', ARRAY['G10','G11','G12']::public.cbe_grade[], false, 'senior_school'::public.cbe_level),
    ('Food and Beverage', 'FOOD_BEV', ARRAY['G10','G11','G12']::public.cbe_grade[], false, 'senior_school'::public.cbe_level),
    ('Motor Vehicle Mechanics', 'MOTOR_VEHICLE', ARRAY['G10','G11','G12']::public.cbe_grade[], false, 'senior_school'::public.cbe_level),
    ('Carpentry and Joinery', 'CARPENTRY', ARRAY['G10','G11','G12']::public.cbe_grade[], false, 'senior_school'::public.cbe_level),
    ('Fire Fighting', 'FIRE', ARRAY['G10','G11','G12']::public.cbe_grade[], false, 'senior_school'::public.cbe_level),
    ('Metalwork', 'METALWORK', ARRAY['G10','G11','G12']::public.cbe_grade[], false, 'senior_school'::public.cbe_level),
    ('Electricity', 'ELEC', ARRAY['G10','G11','G12']::public.cbe_grade[], false, 'senior_school'::public.cbe_level),
    ('Land Surveying', 'SURVEY', ARRAY['G10','G11','G12']::public.cbe_grade[], false, 'senior_school'::public.cbe_level),
    ('Science Laboratory Technology', 'LAB_TECH', ARRAY['G10','G11','G12']::public.cbe_grade[], false, 'senior_school'::public.cbe_level),
    ('Electronics', 'ELEC_2', ARRAY['G10','G11','G12']::public.cbe_grade[], false, 'senior_school'::public.cbe_level),
    ('Printing Technology', 'PRINTING', ARRAY['G10','G11','G12']::public.cbe_grade[], false, 'senior_school'::public.cbe_level),
    ('Crop Production', 'CROP', ARRAY['G10','G11','G12']::public.cbe_grade[], false, 'senior_school'::public.cbe_level)
) AS area(name, code, grades, is_core, education_level)
ON CONFLICT (school_id, name) DO NOTHING;
